local source = {}

source.new = function()
	return setmetatable({}, { __index = source })
end

local emojis = {
	{ emoji = "🙂", text = "Slightly smiling face" },
	{ emoji = "😀", text = "Smiling face" },
	{ emoji = "😃", text = "Smiling face with big eyes" },
	{ emoji = "😄", text = "Smiling face with smiling eyes" },
	{ emoji = "😁", text = "Beaming face with smiling eyes" },
	{ emoji = "😅", text = "Smiling face with tears" },
	{ emoji = "😆", text = "Grinning face" },
	{ emoji = "🤣", text = "Rolling on the floor laughing" },
	{ emoji = "😂", text = "Lauging with tears" },
	{ emoji = "🙃", text = "Upside down face" },
	{ emoji = "😉", text = "Winking face" },
	{ emoji = "😊", text = "Smiling face with smiling eyes" },
	{ emoji = "😇", text = "Smiling face with halo" },
	{ emoji = "😎", text = "Smiling face with sunglasses" },
	{ emoji = "🤓", text = "Nerdy face" },
	{ emoji = "🧐", text = "Face with monocle" },
	{ emoji = "🥳", text = "Partying face" },
	{ emoji = "🥰", text = "Smiling face with hearts" },
	{ emoji = "😍", text = "Smiling face with heart eyes" },
	{ emoji = "🤩", text = "Star-struck" },
	{ emoji = "😘", text = "Face blowing kiss" },
	{ emoji = "😗", text = "Kissing face" },
	{ emoji = "😚", text = "Kissing face with closed eyes" },
	{ emoji = "😙", text = "Kissng face with smiling eyes" },
	{ emoji = "🥲", text = "Smiling face with tears" },
	{ emoji = "😋", text = "Yummy face" },
	{ emoji = "😛", text = "Face with tongue" },
	{ emoji = "😜", text = "WInking face with tongue" },
	{ emoji = "🤪", text = "Zanny face" },
	{ emoji = "😝", text = "Squinting face with tongue" },
	{ emoji = "🤑", text = "Money face with money tongue" },
	{ emoji = "🤗", text = "Hugs" },
	{ emoji = "🤭", text = "Face with hand in mouth" },
	{ emoji = "🤫", text = "Shushing face" },
	{ emoji = "🤔", text = "Thinkin face" },
	{ emoji = "😐", text = "Neutral face" },
	{ emoji = "🤐", text = "Zipped mouth" },
	{ emoji = "🤨", text = "Face with raised eyebrow" },
	{ emoji = "😑", text = "Expressionless face" },
	{ emoji = "😶", text = "Face with no mouth" },
	{ emoji = "😏", text = "Smirking face" },
	{ emoji = "😒", text = "Unamused face" },
	{ emoji = "🙄", text = "Face with rolling eyes" },
	{ emoji = "😬", text = "Grimacing face" },
	{ emoji = "😮", text = "Grimacing face" },
	{ emoji = "🤥", text = "Lying face" },
	{ emoji = "😪", text = "Sleepy face" },
	{ emoji = "😴", text = "Sleeping face" },
	{ emoji = "😌", text = "Relieved face" },
	{ emoji = "😔", text = "Pensive face" },
	{ emoji = "🤤", text = "Drooling face" },
	{ emoji = "😷", text = "Face with mask" },
	{ emoji = "🤒", text = "Face with thermometer" },
	{ emoji = "🤕", text = "Face with bandage" },
	{ emoji = "🤢", text = "Nauseous face" },
	{ emoji = "🤮", text = "Vomiting face" },
	{ emoji = "🤧", text = "Sneezing face" },
	{ emoji = "🥵", text = "Hot face" },
	{ emoji = "🥶", text = "Cold face" },
	{ emoji = "🥴", text = "Woozy face" },
	{ emoji = "😵", text = "Face with crossed-out face" },
	{ emoji = "🤯", text = "Face with exploding head" },
	{ emoji = "😕", text = "Confused face" },
	{ emoji = "😟", text = "Worried face" },
	{ emoji = "🙁", text = "Slightly frowning face" },
	{ emoji = "😮", text = "Face with open mouth" },
	{ emoji = "😯", text = "Hushed face" },
	{ emoji = "😲", text = "Astonished face" },
	{ emoji = "😳", text = "Flushed face" },
	{ emoji = "🥺", text = "Begging face" },
	{ emoji = "😦", text = "Frowning face with open mouth" },
	{ emoji = "😧", text = "Angushed face" },
	{ emoji = "😨", text = "Fearful face" },
	{ emoji = "😰", text = "Anxious face with sweat" },
	{ emoji = "😥", text = "Sad but relieved face" },
	{ emoji = "😢", text = "Crying face" },
	{ emoji = "😭", text = "Loudly crying face" },
	{ emoji = "😱", text = "Screaming face" },
	{ emoji = "😖", text = "Confounded face" },
	{ emoji = "😣", text = "Persevering face" },
	{ emoji = "😞", text = "Disapointed face" },
	{ emoji = "😓", text = "Downcast face with sweat" },
	{ emoji = "😩", text = "Weary face" },
	{ emoji = "😫", text = "Tired face" },
	{ emoji = "🥱", text = "Yawning face" },
	{ emoji = "😤", text = "Face with steam" },
	{ emoji = "😡", text = "Pouting face" },
	{ emoji = "😠", text = "Angry face" },
	{ emoji = "🤬", text = "Face with symbols on mouth" },
	{ emoji = "😈", text = "Smiling face with horns" },
	{ emoji = "👿", text = "Angry face with horns" },
	{ emoji = "💀", text = "Skull" },
	{ emoji = "☠", text = "Skull and cross-bone" },
	{ emoji = "💩", text = "Pile of poo" },
	{ emoji = "🤡", text = "Clown" },
	{ emoji = "👹", text = "Ogre" },
	{ emoji = "👺", text = "Goblin" },
	{ emoji = "👻", text = "Ghost" },
	{ emoji = "👽", text = "Alien" },
	{ emoji = "👾", text = "Alien monster" },
	{ emoji = "🤖", text = "Robot" },
	{ emoji = "😺", text = "Grinnig cat" },
	{ emoji = "😸", text = "Grinning cat with smiling eyes" },
	{ emoji = "😹", text = "Grinning cat with tears" },
	{ emoji = "😻", text = "Smiling cat with heart eyes" },
	{ emoji = "😼", text = "Cat with wry smile" },
	{ emoji = "😽", text = "Kissing cat" },
	{ emoji = "🙀", text = "Weary cat" },
	{ emoji = "😿", text = "Crying cat" },
	{ emoji = "😾", text = "Pouting cat" },
	{ emoji = "🙈", text = "See no evil monkey" },
	{ emoji = "🙉", text = "Hear no evil monkey" },
	{ emoji = "🙊", text = "Speak no evil monkey" },
	{ emoji = "💋", text = "Kiss" },
	{ emoji = "💌", text = "Love letter" },
	{ emoji = "💘", text = "Heart with arrow" },
	{ emoji = "💝", text = "HEart with ribbon" },
	{ emoji = "💖", text = "Sparking heart" },
	{ emoji = "💗", text = "Growing heart" },
	{ emoji = "💓", text = "Beating heart" },
	{ emoji = "💞", text = "Revolving heart" },
	{ emoji = "💕", text = "Two hearts" },
	{ emoji = "💟", text = "Heart decoration" },
	{ emoji = "❣", text = "Heart exclamation" },
	{ emoji = "💔", text = "Broken heart" },
	{ emoji = "❤", text = "Red heart" },
	{ emoji = "🧡", text = "Orange heart" },
	{ emoji = "💛", text = "Yellow heart" },
	{ emoji = "💚", text = "Green heart" },
	{ emoji = "💙", text = "Blue heart" },
	{ emoji = "💜", text = "Purple heart" },
	{ emoji = "🤎", text = "Brown heart" },
	{ emoji = "🖤", text = "Black heart" },
	{ emoji = "🤍", text = "White heart" },
	{ emoji = "💯", text = "Hundred(correct)" },
	{ emoji = "💢", text = "Anger" },
	{ emoji = "💥", text = "collision" },
	{ emoji = "💫", text = "Dizzy" },
	{ emoji = "💦", text = "Sweat droplets" },
	{ emoji = "💨", text = "Dashing away" },
	{ emoji = "🕳", text = "Hole" },
	{ emoji = "💣", text = "Bomb" },
	{ emoji = "💬", text = "Message baloon" },
	{ emoji = "👁️", text = "Eye in speech bubble" },
	{ emoji = "🗨", text = "Left speech bubble" },
	{ emoji = "🗯", text = "Anger bubble" },
	{ emoji = "💭", text = "Thought baloon" },
	{ emoji = "💤", text = "zzz" },
	{ emoji = "👋", text = "Waving hand" },
	{ emoji = "🤚", text = "Raised back of hand" },
	{ emoji = "🖐", text = "Hands with splayed finger" },
	{ emoji = "✋", text = "Raised hand" },
	{ emoji = "🖖", text = "Vulcan salute" },
	{ emoji = "👌", text = "Ok" },
	{ emoji = "🤌", text = "Pinched fingers" },
	{ emoji = "🤏", text = "Pinched hand" },
	{ emoji = "✌ ", text = "Victory hand" },
	{ emoji = "🤞", text = "Crossed fingers" },
	{ emoji = "🤟", text = "Love you" },
	{ emoji = "🤘", text = "Horn sign" },
	{ emoji = "🤙", text = "Call me hand" },
	{ emoji = "👈", text = "Index finger pointing left" },
	{ emoji = "👉", text = "Index finger pointing right" },
	{ emoji = "👆", text = "Index finger pointing up" },
	{ emoji = "👇", text = "Index finger pointing down" },
	{ emoji = "🖕", text = "Middle finger" },
	{ emoji = "☝ ", text = "Forehand Index finger pointing up" },
	{ emoji = "🫵", text = "Index finger pointing at viewer" },
	{ emoji = "👍", text = "Thumbs up" },
	{ emoji = "👎", text = "Thumbs down" },
	{ emoji = "✊", text = "Raised fist" },
	{ emoji = "👊", text = "Fist" },
	{ emoji = "🤛", text = "Left facing fist" },
	{ emoji = "🤜", text = "Right facing fist" },
	{ emoji = "👏", text = "Clapping hands" },
	{ emoji = "🙌", text = "Raised hands" },
	{ emoji = "👐", text = "OPen hands" },
	{ emoji = "🤲", text = "Palms together hands" },
	{ emoji = "🤝", text = "Handshake" },
	{ emoji = "🙏", text = "Praying hands" },
	{ emoji = "✍ ", text = "Writing hands" },
	{ emoji = "💅", text = "Nail polish" },
	{ emoji = "🤳", text = "Selfie hand" },
	{ emoji = "💪", text = "Flexed biceps" },
	{ emoji = "🦾", text = "MEchanical arm" },
	{ emoji = "🦵", text = "Leg" },
	{ emoji = "🦿", text = "Mechanical leg" },
	{ emoji = "🦶", text = "Foot" },
	{ emoji = "👂", text = "Ear" },
	{ emoji = "🦻", text = "Ear with earing aid" },
	{ emoji = "👃", text = "Nose" },
	{ emoji = "🧠", text = "Brain" },
	{ emoji = "👣", text = "Footprint" },
	{ emoji = "🫀", text = "MEchanical heart" },
	{ emoji = "🫁", text = "Lungs" },
	{ emoji = "🦷", text = "Tooth" },
	{ emoji = "🦴", text = "Bone" },
	{ emoji = "👀", text = "Eyes" },
	{ emoji = "👁", text = "Eye" },
	{ emoji = "👅", text = "Nose" },
	{ emoji = "👄", text = "Mouth" },
	{ emoji = "🧑", text = "Person" },
	{ emoji = "👶", text = "Baby" },
	{ emoji = "🧒", text = "Child" },
	{ emoji = "👦", text = "Boy" },
	{ emoji = "👧", text = "Girl" },
	{ emoji = "👱", text = "Person with blonde hair" },
	{ emoji = "👨", text = "Man" },
	{ emoji = "🧔", text = "Bearded person" },
	{ emoji = "👩", text = "Woman" },
	{ emoji = "🧓", text = "Old person" },
	{ emoji = "👴", text = "Old man" },
	{ emoji = "👵", text = "Old woman" },
	{ emoji = "🙍", text = "Person frowning" },
	{ emoji = "🙎", text = "Person pouting" },
	{ emoji = "🙅", text = "Person gesturing no" },
	{ emoji = "🙆", text = "Person stretching" },
	{ emoji = "💁", text = "Person tipping hand" },
	{ emoji = "🙋", text = "Person rainsing hand" },
	{ emoji = "🧏", text = "Deaf person" },
	{ emoji = "🙇", text = "Person bowing" },
	{ emoji = "🤦", text = "Person facepalming" },
	{ emoji = "🤷", text = "Person shrugging" },
	{ emoji = "🚒", text = "Man firefighter" },
	{ emoji = "👮", text = "Police" },
	{ emoji = "🕵", text = "Detective" },
	{ emoji = "💂", text = "Guard" },
	{ emoji = "🥷", text = "Ninja" },
	{ emoji = "👷", text = "Construction worker" },
	{ emoji = "🤴", text = "Prince" },
	{ emoji = "👸", text = "Princess" },
	{ emoji = "👳", text = "Person wearing turban" },
	{ emoji = "👲", text = "Person with skullcap" },
	{ emoji = "🧕", text = "Woman with headscaff" },
	{ emoji = "🤵", text = "Person in tuxedo" },
	{ emoji = "👰", text = "Person in veil" },
	{ emoji = "🤰", text = "Pregnant woman" },
	{ emoji = "🤱", text = "Breast-feeding" },
	{ emoji = "👼", text = "Baby angel" },
	{ emoji = "🎅", text = "Santa claus" },
	{ emoji = "🤶", text = "Mrs Claus" },
	{ emoji = "🦸", text = "Superhero" },
	{ emoji = "🦹", text = "Supervillain" },
	{ emoji = "🧙", text = "Mage" },
	{ emoji = "🧚", text = "Fairy" },
	{ emoji = "🧛", text = "Vampire" },
	{ emoji = "🧜", text = "Merperson" },
	{ emoji = "🧝", text = "Elf" },
	{ emoji = "🧞", text = "Genie" },
	{ emoji = "🧟", text = "Zombie" },
	{ emoji = "💆", text = "Person getting massage" },
	{ emoji = "💇", text = "Person getting haircut" },
	{ emoji = "🚶", text = "Person walking" },
	{ emoji = "🧍", text = "Person standing" },
	{ emoji = "🧎", text = "Person kneeling" },
	{ emoji = "🏃", text = "Person sprinting" },
	{ emoji = "💃", text = "Woman dancing" },
	{ emoji = "🕺", text = "Man dancing" },
	{ emoji = "🕴", text = "Person in suit levitating" },
	{ emoji = "👯", text = "People with bunny ears" },
	{ emoji = "🧖", text = "Person in steaming room" },
	{ emoji = "🧗", text = "Person climbing" },
	{ emoji = "🤺", text = "Person fencing" },
	{ emoji = "🏇", text = "Horse racing" },
	{ emoji = "⛷ ", text = "Skier" },
	{ emoji = "🏂", text = "Snowball" },
	{ emoji = "🏌", text = "Person playing golf" },
	{ emoji = "🏄", text = "Person surfing" },
	{ emoji = "🚣", text = "Person rowing boat" },
	{ emoji = "🏊", text = "Person swimming" },
	{ emoji = "⛹ ", text = "Person bouncing ball" },
	{ emoji = "🏋", text = "Person lifting weight" },
	{ emoji = "🚴", text = "Person cycling" },
	{ emoji = "🚵", text = "Person mountain biking" },
	{ emoji = "🤸", text = "Person catwheeling" },
	{ emoji = "🤼", text = "People wrestling" },
	{ emoji = "🤽", text = "Person playing water polo" },
	{ emoji = "🤾", text = "Person playing handball" },
	{ emoji = "🤹", text = "Person juggling" },
	{ emoji = "🧘", text = "Person lotus position" },
	{ emoji = "🛀", text = "Person bathing" },
	{ emoji = "🛌", text = "Person in bed" },
	{ emoji = "👪", text = "Family" },
	{ emoji = "👭", text = "Women holding hands" },
	{ emoji = "👫", text = "Woman and man holding hands" },
	{ emoji = "👬", text = "Men holding hands" },
	{ emoji = "💏", text = "Kiss" },
	{ emoji = "💑", text = "Couple with heart" },
	{ emoji = "🗣", text = "Person speaking" },
	{ emoji = "👤", text = "Bust in silhouhette" },
	{ emoji = "👥", text = "Busts in silhouette" },
	{ emoji = "🫂", text = "People hugging" },
	{ emoji = "🐵", text = "Monkey face" },
	{ emoji = "🐒", text = "Monkey" },
	{ emoji = "🦍", text = "Gorilla" },
	{ emoji = "🦧", text = "Orangutan" },
	{ emoji = "🐶", text = "Dog face" },
	{ emoji = "🐕", text = "Dog" },
	{ emoji = "🦮", text = "Guide dog" },
	{ emoji = "🦺", text = "Service dog" },
	{ emoji = "🐩", text = "Poodle" },
	{ emoji = "🐺", text = "Wolf" },
	{ emoji = "🦊", text = "Fox" },
	{ emoji = "🦝", text = "Racoon" },
	{ emoji = "🐱", text = "Cat face" },
	{ emoji = "🐈", text = "Cat" },
	{ emoji = "⬛", text = "Black cat" },
	{ emoji = "🦁", text = "Lion" },
	{ emoji = "🐯", text = "Tiger face" },
	{ emoji = "🐅", text = "Tiger" },
	{ emoji = "🐆", text = "Leopard" },
	{ emoji = "🐴", text = "Horse face" },
	{ emoji = "🐎", text = "Horse" },
	{ emoji = "🦄", text = "Unicorn" },
	{ emoji = "🦓", text = "Zebra" },
	{ emoji = "🦌", text = "Deer" },
	{ emoji = "🦬", text = "Bison" },
	{ emoji = "🐮", text = "Cow face" },
	{ emoji = "🐄", text = "Cow" },
	{ emoji = "🐂", text = "Ox" },
	{ emoji = "🐃", text = "Water buffalo" },
	{ emoji = "🐷", text = "Pig face" },
	{ emoji = "🐖", text = "Pig" },
	{ emoji = "🐗", text = "Boar" },
	{ emoji = "🐽", text = "Pig nose" },
	{ emoji = "🐏", text = "Ram" },
	{ emoji = "🐑", text = "Ewe" },
	{ emoji = "🐐", text = "Goat" },
	{ emoji = "🐪", text = "Camel" },
	{ emoji = "🐫", text = "Two hump camel" },
	{ emoji = "🦙", text = "Ilama" },
	{ emoji = "🦒", text = "Giraffe" },
	{ emoji = "🐘", text = "Elephant" },
	{ emoji = "🦣", text = "Mammoth" },
	{ emoji = "🦏", text = "Rhiniceros" },
	{ emoji = "🦛", text = "Hippopotamus" },
	{ emoji = "🐭", text = "Mouse face" },
	{ emoji = "🐁", text = "Mouse" },
	{ emoji = "🐀", text = "Rat" },
	{ emoji = "🐹", text = "Hamster" },
	{ emoji = "🐰", text = "Rabbit face" },
	{ emoji = "🐇", text = "Rabbit" },
	{ emoji = "🐿", text = "Chipmunk" },
	{ emoji = "🦫", text = "Beaver" },
	{ emoji = "🦔", text = "Hedgehog" },
	{ emoji = "🦇", text = "Bat" },
	{ emoji = "🐻", text = "Bear" },
	{ emoji = "❄️ ", text = "Polar bear" },
	{ emoji = "🐨", text = "Koala" },
	{ emoji = "🐼", text = "Panda" },
	{ emoji = "🦥", text = "Sloth" },
	{ emoji = "🦦", text = "Otter" },
	{ emoji = "🦨", text = "Skunk" },
	{ emoji = "🦘", text = "Kangaroo" },
	{ emoji = "🦡", text = "Badger" },
	{ emoji = "🐾", text = "Paw prints" },
	{ emoji = "🦃", text = "Turkey" },
	{ emoji = "🐔", text = "Chicken" },
	{ emoji = "🐓", text = "Rooster" },
	{ emoji = "🐣", text = "Hatching" },
	{ emoji = "🐤", text = "Baby chick" },
	{ emoji = "🐥", text = "Front-facing chick" },
	{ emoji = "🐦", text = "Bird" },
	{ emoji = "🐧", text = "Penguin" },
	{ emoji = "🕊", text = "Dove" },
	{ emoji = "🦅", text = "Eagle" },
	{ emoji = "🦆", text = "Duck" },
	{ emoji = "🦢", text = "Swan" },
	{ emoji = "🦉", text = "Owl" },
	{ emoji = "🦤", text = "Dodo" },
	{ emoji = "🪶", text = "Feather" },
	{ emoji = "🦩", text = "Flamingo" },
	{ emoji = "🦜", text = "Peacock" },
	{ emoji = "🐸", text = "Frog" },
	{ emoji = "🐊", text = "Crocodile" },
	{ emoji = "🐢", text = "Turtle" },
	{ emoji = "🦎", text = "Lizard" },
	{ emoji = "🐍", text = "Snake" },
	{ emoji = "🐲", text = "Dragon face" },
	{ emoji = "🐉", text = "Dragon" },
	{ emoji = "🦕", text = "Sauropod" },
	{ emoji = "🦖", text = "Tyranosaurus" },
	{ emoji = "🐳", text = "Spouting whale" },
	{ emoji = "🐋", text = "Whale" },
	{ emoji = "🐬", text = "Dolphin" },
	{ emoji = "🦭", text = "Seal" },
	{ emoji = "🐟", text = "Fish" },
	{ emoji = "🐠", text = "Tropical fish" },
	{ emoji = "🐡", text = "Blowfish" },
	{ emoji = "🦈", text = "Shark" },
	{ emoji = "🐙", text = "Octopus" },
	{ emoji = "🐚", text = "Spiral shell" },
	{ emoji = "🐌", text = "Snail" },
	{ emoji = "🦋", text = "Butterfly" },
	{ emoji = "🐛", text = "Bug" },
	{ emoji = "🐜", text = "Ant" },
	{ emoji = "🐝", text = "Honeybee" },
	{ emoji = "🪲", text = "Beetle" },
	{ emoji = "🐞", text = "Lady Beetle" },
	{ emoji = "🦗", text = "Cricket" },
	{ emoji = "🪳", text = "Cockroach" },
	{ emoji = "🕷", text = "Spider" },
	{ emoji = "🕸", text = "Spider web" },
	{ emoji = "🦂", text = "Scorpion" },
	{ emoji = "🦟", text = "Mosquito" },
	{ emoji = "🪰", text = "Fly" },
	{ emoji = "🪱", text = "Worm" },
	{ emoji = "🦠", text = "Microbe" },
	{ emoji = "💐", text = "Bouquet" },
	{ emoji = "🌸", text = "Cherry blossom" },
	{ emoji = "💮", text = "White flower" },
	{ emoji = "🏵", text = "Rosette" },
	{ emoji = "🌹", text = "Rose" },
	{ emoji = "🥀", text = "Wilted flower" },
	{ emoji = "🌺", text = "Hibiscus" },
	{ emoji = "🌻", text = "Sunflower" },
	{ emoji = "🌼", text = "Blossom" },
	{ emoji = "🌷", text = "Tulip" },
	{ emoji = "🌱", text = "Seedling" },
	{ emoji = "🪴", text = "Potted plant" },
	{ emoji = "🌲", text = "Evergreen tree" },
	{ emoji = "🌳", text = "Deciduous plant" },
	{ emoji = "🌴", text = "Palm tree" },
	{ emoji = "🌵", text = "Cactus" },
	{ emoji = "🌾", text = "Sheaf of rice" },
	{ emoji = "🌿", text = "Herb" },
	{ emoji = "☘", text = "Shamrock" },
	{ emoji = "🍀", text = "Four leaf clover" },
	{ emoji = "🍁", text = "Maple leaf" },
	{ emoji = "🍂", text = "Fallen leaf" },
	{ emoji = "🍃", text = "Leaf fluttering in wind" },
	{ emoji = "🪴", text = "Empty nest" },
	{ emoji = "🪴", text = "Nest with eggs" },
	{ emoji = "🍇", text = "Grapes" },
	{ emoji = "🍈", text = "Melon" },
	{ emoji = "🍉", text = "Water melon" },
	{ emoji = "🍊", text = "Tangerine" },
	{ emoji = "🍋", text = "Lime" },
	{ emoji = "🍌", text = "Banana" },
	{ emoji = "🍍", text = "Pineapple" },
	{ emoji = "🥭", text = "Mango" },
	{ emoji = "🍎", text = "Red apple" },
	{ emoji = "🍏", text = "Green apple" },
	{ emoji = "🍐", text = "Pear" },
	{ emoji = "🍑", text = "Peach" },
	{ emoji = "🍒", text = "Cherries" },
	{ emoji = "🍓", text = "Strawberries" },
	{ emoji = "🫐", text = "Blueberries" },
	{ emoji = "🥝", text = "Kiwi fruit" },
	{ emoji = "🍅", text = "Tomato" },
	{ emoji = "🫒", text = "Olive" },
	{ emoji = "🥥", text = "Coconut" },
	{ emoji = "🥑", text = "Avocado" },
	{ emoji = "🍆", text = "Eggplant" },
	{ emoji = "🥔", text = "Potato" },
	{ emoji = "🥕", text = "Carrot" },
	{ emoji = "🌽", text = "Corn" },
	{ emoji = "🌶", text = "Pepper" },
	{ emoji = "🫑", text = "Bell pepper" },
	{ emoji = "🥒", text = "Cucumber" },
	{ emoji = "🥬", text = "Leafy green" },
	{ emoji = "🥦", text = "Broccoli" },
	{ emoji = "🧄", text = "Garlic" },
	{ emoji = "🧅", text = "Onion" },
	{ emoji = "🍄", text = "Mushroom" },
	{ emoji = "🥜", text = "Peanuts" },
	{ emoji = "🫑", text = "Beans" },
	{ emoji = "🌰", text = "Chestnut" },
	{ emoji = "🍞", text = "Bread" },
	{ emoji = "🥐", text = "Croissant" },
	{ emoji = "🥖", text = "Baguette bread" },
	{ emoji = "🫓", text = "Flat bread" },
	{ emoji = "🥨", text = "Pretzel" },
	{ emoji = "🥯", text = "Bagel" },
	{ emoji = "🥞", text = "Pancake" },
	{ emoji = "🧇", text = "Waffle" },
	{ emoji = "🧀", text = "Cheese wedge" },
	{ emoji = "🍖", text = "Meat with bone" },
	{ emoji = "🍗", text = "Poultry leg" },
	{ emoji = "🥩", text = "Cut of meat" },
	{ emoji = "🥓", text = "Bacon" },
	{ emoji = "🍔", text = "Hamburger" },
	{ emoji = "🍟", text = "French fries" },
	{ emoji = "🍕", text = "Pizza" },
	{ emoji = "🌭", text = "Hot dog" },
	{ emoji = "🥪", text = "Sandwich" },
	{ emoji = "🌮", text = "Taco" },
	{ emoji = "🌯", text = "Burrito" },
	{ emoji = "🫔", text = "Tamale" },
	{ emoji = "🥙", text = "Stuffed flatbread" },
	{ emoji = "🧆", text = "Falafel" },
	{ emoji = "🥚", text = "Egg" },
	{ emoji = "🍳", text = "Cooking" },
	{ emoji = "🥘", text = "Shallow pan of food" },
	{ emoji = "🍲", text = "Pot of food" },
	{ emoji = "🫕", text = "Fondue" },
	{ emoji = "🥣", text = "Bowl with food" },
	{ emoji = "🥗", text = "Green salad" },
	{ emoji = "🍿", text = "Popcorn" },
	{ emoji = "🧈", text = "Butter" },
	{ emoji = "🧂", text = "Salt" },
	{ emoji = "🥫", text = "Canned food" },
	{ emoji = "🍱", text = "Bento box" },
	{ emoji = "🍘", text = "RIce cracker" },
	{ emoji = "🍙", text = "Rice ball" },
	{ emoji = "🍚", text = "Cooked rice" },
	{ emoji = "🍛", text = "Curry rice" },
	{ emoji = "🍜", text = "Steaming bowl" },
	{ emoji = "🍝", text = "Spaghetti" },
	{ emoji = "🍠", text = "Roasted sweet potato" },
	{ emoji = "🍢", text = "Oden" },
	{ emoji = "🍣", text = "Sushi" },
	{ emoji = "🍤", text = "Fried shrimp" },
	{ emoji = "🍥", text = "Fish cake with swiri" },
	{ emoji = "🥮", text = "Moon cake" },
	{ emoji = "🍡", text = "Dango" },
	{ emoji = "🥟", text = "Dumpling" },
	{ emoji = "🥠", text = "Fortune cookie" },
	{ emoji = "🥡", text = "Take out box" },
	{ emoji = "🦀", text = "Crab" },
	{ emoji = "🦞", text = "Lobster" },
	{ emoji = "🦐", text = "Shrimp" },
	{ emoji = "🦑", text = "Squid" },
	{ emoji = "🦪", text = "Oyster" },
	{ emoji = "🍨", text = "Ice cream" },
	{ emoji = "🍧", text = "Shaved ice cream" },
	{ emoji = "🍦", text = "Soft ice cream" },
	{ emoji = "🍩", text = "Doughnut" },
	{ emoji = "🍪", text = "Cookie" },
	{ emoji = "🎂", text = "Birthday cake" },
	{ emoji = "🍰", text = "Short cake" },
	{ emoji = "🧁", text = "Cup cake" },
	{ emoji = "🥧", text = "Pie" },
	{ emoji = "🍫", text = "Chocoloate" },
	{ emoji = "🍬", text = "Candy" },
	{ emoji = "🍭", text = "Lollipop" },
	{ emoji = "🍮", text = "Custard" },
	{ emoji = "🍯", text = "Honey pot" },
	{ emoji = "🍼", text = "Baby bottle" },
	{ emoji = "🥛", text = "Glass of milk" },
	{ emoji = "☕", text = "Hot beverage" },
	{ emoji = "🫖", text = "Teapot" },
	{ emoji = "🍵", text = "Teacup without handle" },
	{ emoji = "🍶", text = "Sake" },
	{ emoji = "🍾", text = "Bottle with poppin cork" },
	{ emoji = "🍷", text = "Wine glass" },
	{ emoji = "🍸", text = "Cocktail glass" },
	{ emoji = "🍹", text = "Tropical drink" },
	{ emoji = "🍺", text = "Beer mug" },
	{ emoji = "🍻", text = "Clinking beer mug" },
	{ emoji = "🥂", text = "Clinking glasses" },
	{ emoji = "🥃", text = "Tumbler glass" },
	{ emoji = "🥤", text = "Cup with strawberry" },
	{ emoji = "🧋", text = "Bubble tea" },
	{ emoji = "🧃", text = "Beverage box" },
	{ emoji = "🧉", text = "Mate" },
	{ emoji = "🧊", text = "Ice" },
	{ emoji = "🥢", text = "Chopsticks" },
	{ emoji = "🍽", text = "Fork and knife with plate" },
	{ emoji = "🍴", text = "Fork and knife" },
	{ emoji = "🥄", text = "Spoon" },
	{ emoji = "🔪", text = "Kitchen knife" },
	{ emoji = "🧋", text = "Jar" },
	{ emoji = "🏺", text = "Amphora" },
	{ emoji = "🌍", text = "Globe showing Africa and Europe" },
	{ emoji = "🌎", text = "Globe showing Americas" },
	{ emoji = "🌏", text = "Globe showing Asia and Australia" },
	{ emoji = "🌐", text = "Globe with meridians" },
	{ emoji = "🗺", text = "World map" },
	{ emoji = "🧭", text = "Compass" },
	{ emoji = "⛰ ", text = "Mountain" },
	{ emoji = "🏔", text = "Snowcap mountain" },
	{ emoji = "🌋", text = "Volcanic mountain" },
	{ emoji = "🗻", text = "Fuji mountain" },
	{ emoji = "🏕", text = "Camping" },
	{ emoji = "🏖", text = "Beach with umbrella" },
	{ emoji = "🏜", text = "Desert" },
	{ emoji = "🏝", text = "Desertified island" },
	{ emoji = "🏞", text = "National park" },
	{ emoji = "🏟", text = "Stadium" },
	{ emoji = "🏛", text = "Classical building" },
	{ emoji = "🏗", text = "Building construction" },
	{ emoji = "🧱", text = "Brick" },
	{ emoji = "🪨", text = "Rock" },
	{ emoji = "🪵", text = "Wood" },
	{ emoji = "🛖", text = "Hut" },
	{ emoji = "🏘", text = "Houses" },
	{ emoji = "🏚", text = "Derelict house" },
	{ emoji = "🏠", text = "House" },
	{ emoji = "🏡", text = "House with garden" },
	{ emoji = "🏢", text = "Office building" },
	{ emoji = "🏣", text = "Japanese office" },
	{ emoji = "🏤", text = "Post office" },
	{ emoji = "🏥", text = "Hospital" },
	{ emoji = "🏦", text = "Bank" },
	{ emoji = "🏨", text = "Hotel" },
	{ emoji = "🏩", text = "Love hotel" },
	{ emoji = "🏪", text = "Convenience store" },
	{ emoji = "🏫", text = "School" },
	{ emoji = "🏬", text = "Department" },
	{ emoji = "🏭", text = "Factory" },
	{ emoji = "🏯", text = "Japanese castle" },
	{ emoji = "🏰", text = "Castle" },
	{ emoji = "💒", text = "Wedding house" },
	{ emoji = "🗼", text = "Tokyo tower" },
	{ emoji = "🗽", text = "Statue of liberty" },
	{ emoji = "⛪", text = "Church" },
	{ emoji = "🕌", text = "Mosque" },
	{ emoji = "🛕", text = "Hindu temple" },
	{ emoji = "🕍", text = "Synagogue" },
	{ emoji = "⛩ ", text = "Shinto shrine" },
	{ emoji = "🕋", text = "Kaaba" },
	{ emoji = "⛲", text = "Fountain" },
	{ emoji = "⛺", text = "Tent" },
	{ emoji = "🌁", text = "Foggy" },
	{ emoji = "🌃", text = "Night with starrs" },
	{ emoji = "🏙", text = "Citscape" },
	{ emoji = "🌅", text = "Sunrise" },
	{ emoji = "🌄", text = "Sunrise over mountains" },
	{ emoji = "🌆", text = "Cityscape at dusk" },
	{ emoji = "🌇", text = "Sunset" },
	{ emoji = "🌉", text = "Bridge at night" },
	{ emoji = "♨", text = "Hot springs" },
	{ emoji = "🎠", text = "Carousel horse" },
	{ emoji = "🎡", text = "Ferris wheel" },
	{ emoji = "🎢", text = "Roller coaster" },
	{ emoji = "💈", text = "Barber poll" },
	{ emoji = "🎪", text = "Circus tent" },
	{ emoji = "🚂", text = "Locomotive" },
	{ emoji = "🚃", text = "Railway car" },
	{ emoji = "🚄", text = "High speed train" },
	{ emoji = "🚅", text = "Bullet train" },
	{ emoji = "🚆", text = "Train" },
	{ emoji = "🚀", text = "rocket" },
	{ emoji = "🚂", text = "train" },
	{ emoji = "🚊", text = "train" },
	{ emoji = "🚉", text = "train" },
	{ emoji = "✈️", text = "airplane plane" },
	{ emoji = "🛫", text = "airplane plane" },
	{ emoji = "🛬", text = "airplane plane" },
	{ emoji = "🛩", text = "airplane plane" },
	{ emoji = "💺", text = "chair" },
	{ emoji = "🛰", text = "Satelite" },
	{ emoji = "🛸", text = "ufo ovni" },
	{ emoji = "🚁", text = "helicopter" },
	{ emoji = "🛶", text = "canoe" },
	{ emoji = "⛵️", text = "sail" },
	{ emoji = "🚤", text = "boat" },
	{ emoji = "🛥", text = "ship" },
	{ emoji = "🛳", text = "ship" },
	{ emoji = "⛴ ", text = "ship" },
	{ emoji = "🚢", text = "ship" },
	{ emoji = "⚓️", text = "anchor" },
	{ emoji = "🛟", text = "lifesaver" },
	{ emoji = "🪝", text = "hook" },
	{ emoji = "🚇", text = "Metro" },
	{ emoji = "🚈", text = "Light rail" },
	{ emoji = "🚉", text = "Station" },
	{ emoji = "🚊", text = "Tram" },
	{ emoji = "🚝", text = "Monorail" },
	{ emoji = "🚞", text = "Mountain railway" },
	{ emoji = "🚋", text = "Tram car" },
	{ emoji = "🚌", text = "us" },
	{ emoji = "🚍", text = "Oncoming bus" },
	{ emoji = "🚎", text = "Trolley bus" },
	{ emoji = "🚐", text = "Minibus" },
	{ emoji = "🚑", text = "Ambulance" },
	{ emoji = "🚒", text = "Fire engine" },
	{ emoji = "🚓", text = "Police car" },
	{ emoji = "🚔", text = "Oncoming police car" },
	{ emoji = "🚕", text = "Taxi" },
	{ emoji = "🚖", text = "Oncoming taxi" },
	{ emoji = "🚗", text = "Automobile" },
	{ emoji = "🚘", text = "Oncoming automobile" },
	{ emoji = "🚙", text = "Sport utility vehicle" },
	{ emoji = "🛻", text = "Pickup truck" },
	{ emoji = "🚚", text = "Delivery truck" },
	{ emoji = "🚛", text = "Articulated lorry" },
	{ emoji = "🚜", text = "Tractor" },
	{ emoji = "🏎", text = "Racing car" },
	{ emoji = "🏍", text = "Motorcycle" },
	{ emoji = "🛵", text = "Scooter" },
	{ emoji = "🦽", text = "Manual wheelchair" },
	{ emoji = "🦼", text = "Motorized wheelchair" },
	{ emoji = "⌛", text = "Hourglass done" },
	{ emoji = "⏳", text = "Hourglass starting" },
	{ emoji = "⌚", text = "Watch" },
	{ emoji = "⏰", text = "Alarm" },
	{ emoji = "⏱ ", text = "Stopwatch" },
	{ emoji = "⏲ ", text = "Timer clock" },
	{ emoji = "🕰", text = "Mantelpiece clock" },
	{ emoji = "🕛", text = "Twelve O'clock" },
	{ emoji = "🕧", text = "Twelve-thirty" },
	{ emoji = "🕐", text = "One O'clock" },
	{ emoji = "🕜", text = "One-thirty" },
	{ emoji = "🕑", text = "Two O'clock" },
	{ emoji = "🕝", text = "Two-thirty" },
	{ emoji = "🕒", text = "Three O'clock" },
	{ emoji = "🕞", text = "Three-thirty" },
	{ emoji = "🕓", text = "Four O'clock" },
	{ emoji = "🕟", text = "Four-thirty" },
	{ emoji = "🕔", text = "Five O'clock" },
	{ emoji = "🕠", text = "Five-thirty" },
	{ emoji = "🕕", text = "Six O'clock" },
	{ emoji = "🕡", text = "Six-thirty" },
	{ emoji = "🕖", text = "Seven O'clock" },
	{ emoji = "🕢", text = "Seven-thirty" },
	{ emoji = "🕗", text = "Eight O'clock" },
	{ emoji = "🕣", text = "Eight-thirty" },
	{ emoji = "🕘", text = "Nine O'clock" },
	{ emoji = "🕤", text = "Nine-thirty" },
	{ emoji = "🕙", text = "Ten O'clock" },
	{ emoji = "🕥", text = "Ten-thirty" },
	{ emoji = "🕚", text = "Eleven O'clock" },
	{ emoji = "🕦", text = "Eleven-thirty" },
	{ emoji = "🌑", text = "New moon" },
	{ emoji = "🌒", text = "Waxing crescent moon" },
	{ emoji = "🌓", text = "First quarter moon" },
	{ emoji = "🌔", text = "Waxing gibbous moon" },
	{ emoji = "🌕", text = "Full moon" },
	{ emoji = "🌖", text = "Waning gibbous moon" },
	{ emoji = "🌗", text = "Last quarter moon" },
	{ emoji = "🌘", text = "Waning crescent moon" },
	{ emoji = "🌙", text = "Crescent moon" },
	{ emoji = "🌚", text = "New moon face" },
	{ emoji = "🌛", text = "First quarter moon face" },
	{ emoji = "🌜", text = "Last quartermoon face" },
	{ emoji = "🌡", text = "Thermometer" },
	{ emoji = "☀", text = "Sun" },
	{ emoji = "🌝", text = "Full moon face" },
	{ emoji = "🌞", text = "Sun with face" },
	{ emoji = "🪐", text = "Ringed planet" },
	{ emoji = "⭐", text = "Star" },
	{ emoji = "🌟", text = "Glowing star" },
	{ emoji = "🌠", text = "Shooting star" },
	{ emoji = "🌌", text = "Milky way" },
	{ emoji = "☁", text = "Cloud" },
	{ emoji = "⛅", text = "Sun behind cloud" },
	{ emoji = "⛈j", text = "Cloud with lighting and rain" },
	{ emoji = "🌤", text = "Sun behind small cloud" },
	{ emoji = "🌥", text = "Sun behind large cloud" },
	{ emoji = "🌦", text = "Sun behind rain cloud" },
	{ emoji = "🌧", text = "Cloud with rain" },
	{ emoji = "🌨", text = "Cloud with snow" },
	{ emoji = "🌩", text = "Cloud with lighting" },
	{ emoji = "🌪", text = "Tornado" },
	{ emoji = "🌫", text = "Fog" },
	{ emoji = "🌬", text = "Wind face" },
	{ emoji = "🌀", text = "Cyclone" },
	{ emoji = "🌈", text = "Rainbow" },
	{ emoji = "🌂", text = "Closed umbrella" },
	{ emoji = "☂", text = "Umbrella" },
	{ emoji = "☔", text = "Umbrella with raindrops" },
	{ emoji = "⛱", text = "Umbrella on ground" },
	{ emoji = "⚡", text = "High voltage" },
	{ emoji = "❄", text = "Snowflake" },
	{ emoji = "☃", text = "Snowman" },
	{ emoji = "⛄", text = "Snowman without snow" },
	{ emoji = "☄ ", text = "Comet" },
	{ emoji = "🔥", text = "Fire" },
	{ emoji = "💧", text = "Droplet" },
	{ emoji = "🌊", text = "Water wave" },
	{ emoji = "🎃", text = "Jack-o-lantern" },
	{ emoji = "🎄", text = "Christmas tree" },
	{ emoji = "🎆", text = "Fireworks" },
	{ emoji = "🎇", text = "Sparkler" },
	{ emoji = "🧨", text = "Firecracker" },
	{ emoji = "✨", text = "Sparkles" },
	{ emoji = "🎈", text = "Baloon" },
	{ emoji = "🎉", text = "Party popper" },
	{ emoji = "🎊", text = "Confetti ball" },
	{ emoji = "🎋", text = "Tanabata tree" },
	{ emoji = "🎍", text = "Pine decoration" },
	{ emoji = "🎎", text = "Japanese dolls" },
	{ emoji = "🎏", text = "Carp streamer" },
	{ emoji = "🎑", text = "Moon viewing ceremony" },
	{ emoji = "🧧", text = "Red envelope" },
	{ emoji = "🎀", text = "Ribbon" },
	{ emoji = "🎁", text = "Wrapped gift" },
	{ emoji = "🎗", text = "Reminder ribbon" },
	{ emoji = "🎟", text = "Admission ticket" },
	{ emoji = "🎫", text = "Ticket" },
	{ emoji = "🎖", text = "Military medal" },
	{ emoji = "🏆", text = "Trophy" },
	{ emoji = "🏅", text = "Sports medal" },
	{ emoji = "🥇", text = "Gold medal - first position" },
	{ emoji = "🥈", text = "Silver medal - second position" },
	{ emoji = "🥉", text = "Bronze medal - third position" },
	{ emoji = "⚽", text = "Soccer ball" },
	{ emoji = "⚾", text = "Baseball" },
	{ emoji = "🥎", text = "Softball" },
	{ emoji = "🏀", text = "BAsketball" },
	{ emoji = "🏐", text = "Volleyball" },
	{ emoji = "🏈", text = "American football" },
	{ emoji = "🏉", text = "Rugby" },
	{ emoji = "🎾", text = "Tennis" },
	{ emoji = "🥏", text = "Flying disk" },
	{ emoji = "🎳", text = "Bowling" },
	{ emoji = "🏏", text = "Cricket" },
	{ emoji = "🏑", text = "Field hockey" },
	{ emoji = "🏒", text = "Ice hockey" },
	{ emoji = "🥍", text = "Lacrose" },
	{ emoji = "🏓", text = "Ping pong" },
	{ emoji = "🏸", text = "Badminton" },
	{ emoji = "🥊", text = "Boxing glove" },
	{ emoji = "🥋", text = "Martial arts uniform" },
	{ emoji = "🥅", text = "Goal net" },
	{ emoji = "⛳", text = "Flag in a hole" },
	{ emoji = "⛸", text = "Ice skate" },
	{ emoji = "🎣", text = "Fishing poll" },
	{ emoji = "🤿", text = "Driving mask" },
	{ emoji = "🎽", text = "Running shirt" },
	{ emoji = "🎿", text = "Skis" },
	{ emoji = "🛷", text = "Sled" },
	{ emoji = "🥌", text = "Curling stone" },
	{ emoji = "🎯", text = "Bullseye" },
	{ emoji = "🪀", text = "Yo-yo" },
	{ emoji = "🪁", text = "Kite" },
	{ emoji = "🎱", text = "8 ball" },
	{ emoji = "🔮", text = "Crystal ball" },
	{ emoji = "🪄", text = "Magic wand" },
	{ emoji = "🧿", text = "Nazar amulet" },
	{ emoji = "🪄", text = "Hamsa" },
	{ emoji = "🎮", text = "Video game pad" },
	{ emoji = "🕹", text = "Joystick" },
	{ emoji = "🎰", text = "Slot machine" },
	{ emoji = "🎲", text = "Game die" },
	{ emoji = "🧩", text = "Puxxle piece" },
	{ emoji = "🧸", text = "Teddy bear" },
	{ emoji = "🪅", text = "Pinata" },
	{ emoji = "🪆", text = "Mirror" },
	{ emoji = "🪆", text = "Nesting doll" },
	{ emoji = "♠", text = "Spade suit" },
	{ emoji = "♥", text = "Heart suit" },
	{ emoji = "♣", text = "Club suit" },
	{ emoji = "♟", text = "Chess pawn" },
	{ emoji = "🃏", text = "Joker" },
	{ emoji = "🀄", text = "Mahjong red dragon" },
	{ emoji = "🎴", text = "Flower playing cards" },
	{ emoji = "🎭", text = "Performing arts" },
	{ emoji = "🖼", text = "Framed picture" },
	{ emoji = "🎨", text = "Artist pallete" },
	{ emoji = "🧵", text = "Thread" },
	{ emoji = "🪡", text = "Sewing needle with thred" },
	{ emoji = "🧶", text = "Yarn" },
	{ emoji = "🪢", text = "Knot" },
	{ emoji = "👓", text = "Glasses" },
	{ emoji = "🕶", text = "Sunglasses" },
	{ emoji = "🥽", text = "Googles" },
	{ emoji = "🥼", text = "Lab coat" },
	{ emoji = "🦺", text = "Safety vest" },
	{ emoji = "👔", text = "Necktie" },
	{ emoji = "👕", text = "T-shirt" },
	{ emoji = "👖", text = "Jeans" },
	{ emoji = "🧣", text = "Scarf" },
	{ emoji = "🧤", text = "Gloves" },
	{ emoji = "🧥", text = "Coat" },
	{ emoji = "🧦", text = "Socks" },
	{ emoji = "👗", text = "Dress" },
	{ emoji = "👘", text = "Kimono" },
	{ emoji = "🥻", text = "Sari" },
	{ emoji = "🩱", text = "One piece suit" },
	{ emoji = "🩲", text = "Briefs" },
	{ emoji = "🩳", text = "Shorts" },
	{ emoji = "👙", text = "Bikini" },
	{ emoji = "👚", text = "Woman's cloth" },
	{ emoji = "👛", text = "Purse" },
	{ emoji = "👜", text = "Handbag" },
	{ emoji = "👝", text = "Clutch bag" },
	{ emoji = "🛍", text = "Shopping bags" },
	{ emoji = "🎒", text = "Backpack" },
	{ emoji = "🩴", text = "Thong sandals" },
	{ emoji = "👞", text = "Man's shoe" },
	{ emoji = "👟", text = "Running shoe" },
	{ emoji = "🥾", text = "Hiking boot" },
	{ emoji = "🥿", text = "Flat shoe" },
	{ emoji = "👠", text = "High-heeled shoe" },
	{ emoji = "👡", text = "Woman's sandal" },
	{ emoji = "🩰", text = "Ballet shoes" },
	{ emoji = "👢", text = "Woman's boot" },
	{ emoji = "👑", text = "Crown" },
	{ emoji = "👒", text = "Woman's hat" },
	{ emoji = "🎩", text = "Top hat" },
	{ emoji = "🎓", text = "Graduation cap" },
	{ emoji = "🧢", text = "Billed cap" },
	{ emoji = "🪖", text = "Military helmet" },
	{ emoji = "⛑ ", text = "Rescuew worker's helmet" },
	{ emoji = "📿", text = "PRayer beads" },
	{ emoji = "💄", text = "Lipstick" },
	{ emoji = "💍", text = "Ring" },
	{ emoji = "💎", text = "Gemstone" },
	{ emoji = "🔇", text = "Muted speaker" },
	{ emoji = "🔈", text = "Low volume speaker" },
	{ emoji = "🔉", text = "Mid volume speaker" },
	{ emoji = "🔊", text = "High volume speaker" },
	{ emoji = "📢", text = "Loudspeaker" },
	{ emoji = "📣", text = "Megaphone" },
	{ emoji = "📯", text = "Postal horn" },
	{ emoji = "🔔", text = "Bell" },
	{ emoji = "🔕", text = "Bell with slash" },
	{ emoji = "🎼", text = "Musical score" },
	{ emoji = "🎵", text = "Musical note" },
	{ emoji = "🎶", text = "Musical notes" },
	{ emoji = "🎙", text = "Studio microphone" },
	{ emoji = "🎚", text = "Level slider" },
	{ emoji = "🎛", text = "Control knobs" },
	{ emoji = "🎤", text = "Microphone" },
	{ emoji = "🎧", text = "Headphone" },
	{ emoji = "📻", text = "Radio" },
	{ emoji = "🎷", text = "Saxophone" },
	{ emoji = "🪗", text = "Accordion" },
	{ emoji = "🎸", text = "Guitar" },
	{ emoji = "🎹", text = "Musical keyboard" },
	{ emoji = "🎺", text = "Trumpet" },
	{ emoji = "🎻", text = "Violin" },
	{ emoji = "🪕", text = "Banjo" },
	{ emoji = "🥁", text = "Drum" },
	{ emoji = "🪘", text = "Long drum" },
	{ emoji = "📱", text = "Mobile phone" },
	{ emoji = "📲", text = "MObile phone with arrow" },
	{ emoji = "☎ ", text = "Telephone" },
	{ emoji = "📞", text = "Telephone receiver" },
	{ emoji = "📟", text = "Pager" },
	{ emoji = "📠", text = "Fax machine" },
	{ emoji = "🔋", text = "Full battery" },
	{ emoji = "🪫", text = "Low battery" },
	{ emoji = "🔌", text = "Electric plug" },
	{ emoji = "💻", text = "Laptop" },
	{ emoji = "🖥", text = "Desktop computer" },
	{ emoji = "🖨", text = "Printer" },
	{ emoji = "⌨", text = "Keyboard" },
	{ emoji = "🖱", text = "Mouse" },
	{ emoji = "🖲", text = "Trackball" },
	{ emoji = "💽", text = "Computer disk" },
	{ emoji = "💾", text = "Floppy disk" },
	{ emoji = "💿", text = "Optical disk" },
	{ emoji = "📀", text = "DVD" },
	{ emoji = "🧮", text = "Abacus" },
	{ emoji = "🎥", text = "Movie camera" },
	{ emoji = "🎞", text = "Film frames" },
	{ emoji = "📽", text = "Film Projector" },
	{ emoji = "🎬", text = "Clapper board" },
	{ emoji = "📺", text = "Television" },
	{ emoji = "📷", text = "Camera" },
	{ emoji = "📸", text = "Camera with flash" },
	{ emoji = "📹", text = "Video camera" },
	{ emoji = "📼", text = "Video cassete" },
	{ emoji = "🔍", text = "Magnifying glass tilted left" },
	{ emoji = "🔎", text = "Magnifying glass tilted right" },
	{ emoji = "🕯", text = "Candle" },
	{ emoji = "💡", text = "Light bulb" },
	{ emoji = "🔦", text = "Flashlight" },
	{ emoji = "🏮", text = "Red pepper lantern" },
	{ emoji = "🪔", text = "Diya lamp" },
	{ emoji = "📔", text = "Notebook with decorative cover" },
	{ emoji = "📕", text = "Closed notebook" },
	{ emoji = "📖", text = "Opened notebook" },
	{ emoji = "📗", text = "Green book" },
	{ emoji = "📘", text = "Blue book" },
	{ emoji = "📙", text = "Orange book" },
	{ emoji = "📚", text = "Orange books" },
	{ emoji = "📓", text = "Notebook" },
	{ emoji = "📒", text = "Ledger" },
	{ emoji = "📃", text = "Page with curl" },
	{ emoji = "📜", text = "Scroll" },
	{ emoji = "📄", text = "Page facing up" },
	{ emoji = "📰", text = "Newspaper" },
	{ emoji = "🗞", text = "Rolled-up newspaper" },
	{ emoji = "📑", text = "Bookmark tabs" },
	{ emoji = "🔖", text = "Bookmark" },
	{ emoji = "🏷", text = "Label" },
	{ emoji = "💰", text = "Money bag" },
	{ emoji = "🪙", text = "Coin" },
	{ emoji = "💴", text = "Yen banknote" },
	{ emoji = "💵", text = "Dollar banknote" },
	{ emoji = "💶", text = "Euro banknote" },
	{ emoji = "💷", text = "Pound banknote" },
	{ emoji = "💸", text = "Money with wings" },
	{ emoji = "💳", text = "Credit card" },
	{ emoji = "🧾", text = "Receipt" },
	{ emoji = "💹", text = "Chart increase woth Yen" },
	{ emoji = "✉", text = "Envelope" },
	{ emoji = "📧", text = "e-mail" },
	{ emoji = "📩", text = "Envelope with arrow" },
	{ emoji = "📤", text = "Outbox tray" },
	{ emoji = "📥", text = "Inbox tray" },
	{ emoji = "📦", text = "Package" },
	{ emoji = "📫", text = "Closed mailbox with raised flag" },
	{ emoji = "📪", text = "Closed mailbox with lowered flag" },
	{ emoji = "📬", text = "Open mailbox with raised flag" },
	{ emoji = "📭", text = "Open mailbox with lowered flag" },
	{ emoji = "📮", text = "Postbox" },
	{ emoji = "🗳", text = "Ballot box with ballot" },
	{ emoji = "✏", text = "Pencil" },
	{ emoji = "✒", text = "Black nib" },
	{ emoji = "🖋", text = "Fountain pen" },
	{ emoji = "🖊", text = "Pen" },
	{ emoji = "🖌", text = "Paintbrush" },
	{ emoji = "🖍", text = "Crayon" },
	{ emoji = "📝", text = "Memo" },
	{ emoji = "💼", text = "Briefcase" },
	{ emoji = "📁", text = "File folder" },
	{ emoji = "📂", text = "Open the folder" },
	{ emoji = "🗂", text = "Card index dividers" },
	{ emoji = "📅", text = "Calender" },
	{ emoji = "📆", text = "Tear off calender" },
	{ emoji = "📇", text = "Card index" },
	{ emoji = "📈", text = "Increasing chart" },
	{ emoji = "📉", text = "Decreasing chart" },
	{ emoji = "📊", text = "Bar chart" },
	{ emoji = "📋", text = "Clipboard" },
	{ emoji = "📌", text = "Pushpin" },
	{ emoji = "📍", text = "Round pushpin" },
	{ emoji = "📎", text = "Paperclip" },
	{ emoji = "🖇", text = "Linked paperclips" },
	{ emoji = "📏", text = "Straight ruler" },
	{ emoji = "📐", text = "Triangular ruler" },
	{ emoji = "✂", text = "Scissors" },
	{ emoji = "🗃", text = "Card file box" },
	{ emoji = "🗄", text = "File cabinet" },
	{ emoji = "🗑", text = "Waste basket" },
	{ emoji = "🔒", text = "Locked" },
	{ emoji = "🔓", text = "Unlocked" },
	{ emoji = "🔏", text = "Locked with pen" },
	{ emoji = "🔐", text = "Locked with key" },
	{ emoji = "🔑", text = "Key" },
	{ emoji = "🗝", text = "Old key" },
	{ emoji = "🔨", text = "Hammer" },
	{ emoji = "🪓", text = "Axe" },
	{ emoji = "⛏", text = "Pick" },
	{ emoji = "⚒", text = "Hammer and pick" },
	{ emoji = "🛠", text = "Hammer and wrench" },
	{ emoji = "🗡", text = "Sword" },
	{ emoji = "⚔", text = "Crossed swords" },
	{ emoji = "🔫", text = "Water gun" },
	{ emoji = "🪃", text = "Boomerang" },
	{ emoji = "🏹", text = "Bow and arrow" },
	{ emoji = "🛡", text = "Shield" },
	{ emoji = "🪚", text = "Carpentry saw" },
	{ emoji = "🔧", text = "Wrench" },
	{ emoji = "🪛", text = "Screwdriver" },
	{ emoji = "🔩", text = "Bolt and nut" },
	{ emoji = "⚙", text = "Wheel" },
	{ emoji = "🗜", text = "Clamp" },
	{ emoji = "⚖", text = "Balance scale" },
	{ emoji = "🦯", text = "White cane" },
	{ emoji = "🔗", text = "Link" },
	{ emoji = "⛓", text = "Chains" },
	{ emoji = "🪝", text = "Hook" },
	{ emoji = "🧰", text = "Toolbox" },
	{ emoji = "🧲", text = "Magnet" },
	{ emoji = "🪜", text = "Ladder" },
	{ emoji = "⚗", text = "Alembic" },
	{ emoji = "🧪", text = "Test tube" },
	{ emoji = "🧫", text = "Petri dish" },
	{ emoji = "🧬", text = "DNA" },
	{ emoji = "🔬", text = "Microscope" },
	{ emoji = "🔭", text = "Telescope" },
	{ emoji = "📡", text = "Satelite antenna" },
	{ emoji = "💉", text = "Syringe" },
	{ emoji = "🩸", text = "A droplet of blood" },
	{ emoji = "💊", text = "Pill" },
	{ emoji = "🩹", text = "Adhesive bandage" },
	{ emoji = "🩼", text = "Clutch" },
	{ emoji = "🩺", text = "Stethoscope" },
	{ emoji = "🩻", text = "X-ray" },
	{ emoji = "🚪", text = "Door" },
	{ emoji = "🛗", text = "Elevator" },
	{ emoji = "🪞", text = "Mirror" },
	{ emoji = "🪟", text = "Window" },
	{ emoji = "🛏", text = "Bed" },
	{ emoji = "🛋", text = "Couch and lamp" },
	{ emoji = "🪑", text = "Chair" },
	{ emoji = "🚽", text = "Toilet" },
	{ emoji = "🪠", text = "Plunger" },
	{ emoji = "🚿", text = "Shower" },
	{ emoji = "🛁", text = "Bathtub" },
	{ emoji = "🪤", text = "Mouse trap" },
	{ emoji = "🪒", text = "Razor" },
	{ emoji = "🧴", text = "Lotion bottle" },
	{ emoji = "🧷", text = "Safety pin" },
	{ emoji = "🧹", text = "Broom" },
	{ emoji = "🧺", text = "Basket" },
	{ emoji = "🧻", text = "Roll of paper" },
	{ emoji = "🪣", text = "Bucket" },
	{ emoji = "🧼", text = "Soap" },
	{ emoji = "🫧", text = "Bubbles" },
	{ emoji = "🪥", text = "Toothbrush" },
	{ emoji = "🧽", text = "Sponge" },
	{ emoji = "🧯", text = "Fire extinguisher" },
	{ emoji = "🛒", text = "Shopping cart" },
	{ emoji = "🚬", text = "Cigarette" },
	{ emoji = "⚰", text = "Casket" },
	{ emoji = "🪦", text = "Headstone" },
	{ emoji = "⚱", text = "Funeral urn" },
	{ emoji = "🗿", text = "Mole" },
	{ emoji = "🪧", text = "Placard" },
	{ emoji = "🪪", text = "ID Card" },
	{ emoji = "🏧", text = "ATM Sign" },
	{ emoji = "🚮", text = "Litter in bin" },
	{ emoji = "🚰", text = "Portable water" },
	{ emoji = "♿", text = "Wheelchair symbol" },
	{ emoji = "🚹", text = "Men's room symbol" },
	{ emoji = "🚺", text = "Women's room symbol" },
	{ emoji = "🚻", text = "Restroom symbol" },
	{ emoji = "🚼", text = "Baby symbol" },
	{ emoji = "🚾", text = "Water closet" },
	{ emoji = "🛂", text = "Passport control" },
	{ emoji = "🛂", text = "Customs" },
	{ emoji = "🛄", text = "Baggage claim" },
	{ emoji = "🛅", text = "Left laugage" },
	{ emoji = "⚠", text = "Warning" },
	{ emoji = "🚸", text = "Children crossing" },
	{ emoji = "⛔", text = "No entry" },
	{ emoji = "🚫", text = "Prohibited" },
	{ emoji = "🚳", text = "No bicycles" },
	{ emoji = "🚭", text = "No smoking" },
	{ emoji = "🚯", text = "No littering" },
	{ emoji = "🚱", text = "Non-portable water" },
	{ emoji = "🚷", text = "No pedestrians" },
	{ emoji = "📵", text = "No mobile phones" },
	{ emoji = "🔞", text = "No one under 18" },
	{ emoji = "☢", text = "Radioactive" },
	{ emoji = "☣", text = "Biohazard" },
	{ emoji = "⬆", text = "Up Arrow" },
	{ emoji = "↗", text = "Up-right arrow" },
	{ emoji = "➡", text = "Right arrow" },
	{ emoji = "↘", text = "Down-right arrow" },
	{ emoji = "⬇", text = "Down arrow" },
	{ emoji = "↙", text = "Down-left arrow" },
	{ emoji = "⬅", text = "Left arrow" },
	{ emoji = "↖", text = "Up-left arrow" },
	{ emoji = "↕", text = "Up-down arrow" },
	{ emoji = "↔", text = "Left arrow" },
	{ emoji = "↩", text = "Right arrow curving left" },
	{ emoji = "↪", text = "Left arrow curving right" },
	{ emoji = "⤴", text = "Right arrow curving up" },
	{ emoji = "⤵", text = "Right arrow curving down" },
	{ emoji = "🔃", text = "Clockwise vertical arrow" },
	{ emoji = "🔄", text = "Counterclockwise arrows button" },
	{ emoji = "🔙", text = "Back arrow" },
	{ emoji = "🔚", text = "End arrow" },
	{ emoji = "🔛", text = "On arrow" },
	{ emoji = "🔜", text = "Soon arrow" },
	{ emoji = "🔝", text = "Top arrow" },
	{ emoji = "🛐", text = "Place of worship" },
	{ emoji = "⚛", text = "Atom symbol" },
	{ emoji = "🕉", text = "OM" },
	{ emoji = "✡", text = "Star of David" },
	{ emoji = "☸", text = "Wheel of Dharma" },
	{ emoji = "☯", text = "Yin yang" },
	{ emoji = "✝", text = "Latin cross" },
	{ emoji = "☦", text = "ORthodox cross" },
	{ emoji = "☪", text = "Star and cresent moon" },
	{ emoji = "☮", text = "Peace" },
	{ emoji = "🕎", text = "Menorah" },
	{ emoji = "🔯", text = "Six-pointed star" },
	{ emoji = "♈", text = "Aries" },
	{ emoji = "♉", text = "Taurus" },
	{ emoji = "♊", text = "Gemini" },
	{ emoji = "♋", text = "Cancer" },
	{ emoji = "♌", text = "Leo" },
	{ emoji = "♍", text = "Virgo" },
	{ emoji = "♎", text = "Libra" },
	{ emoji = "♏", text = "Scorpio" },
	{ emoji = "♐", text = "Sagittarius" },
	{ emoji = "♑", text = "Capricon" },
	{ emoji = "♒", text = "Acquarius" },
	{ emoji = "♓", text = "Pisces" },
	{ emoji = "⛎", text = "Ophiucus" },
	{ emoji = "🔀", text = "Shuffle tracks" },
	{ emoji = "🔁", text = "Repeat all" },
	{ emoji = "🔂", text = "Repeat one" },
	{ emoji = "▶", text = "Play" },
	{ emoji = "⏸ ", text = "Pause" },
	{ emoji = "⏩", text = "Fast-forward" },
	{ emoji = "⏭ ", text = "Next track" },
	{ emoji = "⏯ ", text = "Play or pause" },
	{ emoji = "◀", text = "Reverse" },
	{ emoji = "⏪", text = "Fast-reverse" },
	{ emoji = "⏮ ", text = "Previous track" },
	{ emoji = "🔼", text = "Upwards" },
	{ emoji = "⏫", text = "Fst-up" },
	{ emoji = "🔽", text = "Downwards" },
	{ emoji = "⏬", text = "Fast down" },
	{ emoji = "⏹ ", text = "Stop" },
	{ emoji = "⏺ ", text = "Record" },
	{ emoji = "⏏", text = "Eject" },
	{ emoji = "🎦", text = "Cinema" },
	{ emoji = "🔅", text = "Dim" },
	{ emoji = "🔆", text = "Bright" },
	{ emoji = "📶", text = "Network antenna bars" },
	{ emoji = "📳", text = "Vibration mode" },
	{ emoji = "📴", text = "Mobile phone off" },
	{ emoji = "♀", text = "Female" },
	{ emoji = "♂", text = "Male" },
	{ emoji = "⚧", text = "Transgender" },
	{ emoji = "✖", text = "Times" },
	{ emoji = "➕", text = "Plus" },
	{ emoji = "➖", text = "Minus" },
	{ emoji = "➗", text = "Divide" },
	{ emoji = "🟰", text = "Equals" },
	{ emoji = "♾", text = "Infinity" },
	{ emoji = "‼", text = "Double exclamation" },
	{ emoji = "⁉", text = "Exclamation and question mark" },
	{ emoji = "❓", text = "Red question mark" },
	{ emoji = "❔", text = "White question mark" },
	{ emoji = "❗", text = "Red exclamation mark" },
	{ emoji = "❕", text = "White exclamation mark" },
	{ emoji = "〰", text = "Wavy dash" },
	{ emoji = "💱", text = "Currency exchange" },
	{ emoji = "💲", text = "Heavy green dollar sign" },
	{ emoji = "⚕", text = "Medical symbol" },
	{ emoji = "♻", text = "Recycling symbol" },
	{ emoji = "⚜", text = "Fleur-de-lis" },
	{ emoji = "🔱", text = "Trident" },
	{ emoji = "📛", text = "Name badge" },
	{ emoji = "🔰", text = "Japanese symbol for beginner" },
	{ emoji = "⭕", text = "Hollow red circle" },
	{ emoji = "✅", text = "Green box with checkmark" },
	{ emoji = "☑", text = "Blue box with checkmark" },
	{ emoji = "✔", text = "Checkmark" },
	{ emoji = "❌", text = "Crossmark" },
	{ emoji = "❎", text = "Green crossmark" },
	{ emoji = "➰", text = "Curly loop" },
	{ emoji = "➿", text = "Double curly loop" },
	{ emoji = "〽", text = "PArt alternation mark" },
	{ emoji = "✳", text = "Eight-spoked asterik" },
	{ emoji = "✴", text = "Eight-pointed star" },
	{ emoji = "❇", text = "Sparkle" },
	{ emoji = "©", text = "Copyright symbol" },
	{ emoji = "®", text = "Registered" },
	{ emoji = "™", text = "Trademark" },
	{ emoji = "#️⃣ ", text = "Keycap #" },
	{ emoji = "*️⃣ ", text = "Keycap *" },
	{ emoji = "0️⃣ ", text = "Keycap 0" },
	{ emoji = "1️⃣ ", text = "Keycap 1" },
	{ emoji = "2️⃣ ", text = "Keycap 2" },
	{ emoji = "3️⃣ ", text = "Keycap 3" },
	{ emoji = "4️⃣ ", text = "Keycap 4" },
	{ emoji = "5️⃣ ", text = "Keycap 5" },
	{ emoji = "6️⃣ ", text = "Keycap 6" },
	{ emoji = "7️⃣ ", text = "Keycap 7" },
	{ emoji = "8️⃣ ", text = "Keycap 8" },
	{ emoji = "9️⃣ ", text = "Keycap 9" },
	{ emoji = "🔟", text = "10 Keycap" },
	{ emoji = "🔠", text = "Input Latin uppercase" },
	{ emoji = "🔡", text = "Input Latin lowercase" },
	{ emoji = "🔢", text = "Input numbers" },
	{ emoji = "🔣", text = "Input symbols" },
	{ emoji = "🔤", text = "Input Latin letters" },
	{ emoji = "🅰 ", text = "blood type" },
	{ emoji = "🆎", text = "AB blood type" },
	{ emoji = "🅱 ", text = "blood type" },
	{ emoji = "🅾 ", text = "blood type" },
	{ emoji = "🆑", text = "CL button" },
	{ emoji = "🆒", text = "Cool button" },
	{ emoji = "🆓", text = "Free button" },
	{ emoji = "ℹ", text = "Info button" },
	{ emoji = "🆔", text = "ID button" },
	{ emoji = "Ⓜ ", text = "Circled M" },
	{ emoji = "🆕", text = "New button" },
	{ emoji = "🆖", text = "NG button" },
	{ emoji = "🆗", text = "OK button" },
	{ emoji = "🅿 ", text = "button" },
	{ emoji = "🆘", text = "SOS button" },
	{ emoji = "🆙", text = "UP! button" },
	{ emoji = "🆚", text = "VS Button" },
	{ emoji = "🈁", text = "Japanese here button" },
	{ emoji = "🈂", text = "Japanese service charge button" },
	{ emoji = "🈷", text = "Japanese monthly amount button" },
	{ emoji = "🈶", text = "Japanese not free of charge button" },
	{ emoji = "🈯", text = "Japanese reserved button" },
	{ emoji = "🉐", text = "Japanese bargain button" },
	{ emoji = "🈹", text = "Japanese discount button" },
	{ emoji = "🈚", text = "Japanese free of charge button" },
	{ emoji = "🈲", text = "Japanese prohibited button" },
	{ emoji = "🉑", text = "Japanese acceptable button" },
	{ emoji = "🈸", text = "Japanese application button" },
	{ emoji = "🈴", text = "Japanese passing grade button" },
	{ emoji = "🈳", text = "Japanese vacancy button" },
	{ emoji = "㊗", text = "Japanese congratulations button" },
	{ emoji = "㊙", text = "Japanese secret button" },
	{ emoji = "🈺", text = "Japanese open for business button" },
	{ emoji = "🈵", text = "Japanese no vacancy button" },
	{ emoji = "🔴", text = "Red circle" },
	{ emoji = "🟠", text = "Orange circle" },
	{ emoji = "🟡", text = "Yellow circle" },
	{ emoji = "🟢", text = "Green circle" },
	{ emoji = "🔵", text = "Blue circle" },
	{ emoji = "🟣", text = "Purple circle" },
	{ emoji = "🟤", text = "Brown circle" },
	{ emoji = "⚫", text = "Black circle" },
	{ emoji = "⚪", text = "White circle" },
	{ emoji = "🟥", text = "Red square" },
	{ emoji = "🟧", text = "Orange square" },
	{ emoji = "🟨", text = "Yellow square" },
	{ emoji = "🟩", text = "Green square" },
	{ emoji = "🟦", text = "Blue square" },
	{ emoji = "🟪", text = "Purple square" },
	{ emoji = "🟫", text = "Brown square" },
	{ emoji = "⬛", text = "Black square" },
	{ emoji = "⬜", text = "White square" },
	{ emoji = "🔶", text = "Large orange diamond" },
	{ emoji = "🔷", text = "Large blue diamond" },
	{ emoji = "🔸", text = "Small orange diamond" },
	{ emoji = "🔹", text = "Small blue diamond" },
	{ emoji = "🔺", text = "Red triangle pointed up" },
	{ emoji = "🔻", text = "Red triangle pointed down" },
	{ emoji = "💠", text = "Diamond with a dot" },
	{ emoji = "🔘", text = "Radio button" },
	{ emoji = "🔳", text = "White square button" },
	{ emoji = "🔲", text = "Black square button" },
	{ emoji = "🏁", text = "Chequered flag" },
	{ emoji = "🚩", text = "Triangular flag" },
	{ emoji = "🎌", text = "Crossed flag" },
	{ emoji = "🏴", text = "Black flag" },
	{ emoji = "🏳", text = "White flag" },
	{ emoji = "🌈", text = "Rainbow flag" },
	{ emoji = "⚧️ ", text = "Transgender flag" },
	{ emoji = "☠️ ", text = "Pirate flag" },
	{ emoji = "🇦🇨", text = "Ascension Island flag" },
	{ emoji = "🇦🇩", text = "Andorra flag" },
	{ emoji = "🇦🇪", text = "UAE flag" },
	{ emoji = "🇦🇫", text = "Afghanistan flag" },
	{ emoji = "🇦🇬", text = "Antigua and Berbuda flag" },
	{ emoji = "🇦🇮", text = "Anguila flag" },
	{ emoji = "🇦🇱", text = "Albania flag" },
	{ emoji = "🇦🇲", text = "Armenia flag" },
	{ emoji = "🇦🇴", text = "Angola flag" },
	{ emoji = "🇦🇶", text = "Antarctica flag" },
	{ emoji = "🇦🇷", text = "Argentina flag" },
	{ emoji = "🇦🇸", text = "American Samoa flag" },
	{ emoji = "🇦🇹", text = "Austria flag" },
	{ emoji = "🇦🇺", text = "Australia flag" },
	{ emoji = "🇦🇼", text = "Aruba flag" },
	{ emoji = "🇦🇽", text = "Åland Islands flag" },
	{ emoji = "🇦🇿", text = "Azerbaijan flag" },
	{ emoji = "🇧🇦", text = "Bosnia flag" },
	{ emoji = "🇧🇧", text = "Barbados flag" },
	{ emoji = "🇧🇩", text = "Bangladesh flag" },
	{ emoji = "🇧🇪", text = "Belgium flag" },
	{ emoji = "🇧🇫", text = "Burkina Faso flag" },
	{ emoji = "🇧🇬", text = "Bulgaria flag" },
	{ emoji = "🇧🇭", text = "Bahrain flag" },
	{ emoji = "🇧🇮", text = "Burundi flag" },
	{ emoji = "🇧🇯", text = "Benin Republic flag" },
	{ emoji = "🇧🇱", text = "St. Barthélemy" },
	{ emoji = "🇧🇲", text = "Bermuda flag" },
	{ emoji = "🇧🇳", text = "Brunei flag" },
	{ emoji = "🇧🇴", text = "Bolivia flag" },
	{ emoji = "🇧🇶", text = "Caribbean Netherlands flag" },
	{ emoji = "🇧🇷", text = "Brazil flag" },
	{ emoji = "🇧🇸", text = "Bahamas flag" },
	{ emoji = "🇧🇹", text = "Bhutan flag" },
	{ emoji = "🇧🇻", text = "Bouvet Island flag" },
	{ emoji = "🇧🇼", text = "Botswana flag" },
	{ emoji = "🇧🇾", text = "Belarus flag" },
	{ emoji = "🇧🇿", text = "Belize flag" },
	{ emoji = "🇨🇦", text = "Canada flag" },
	{ emoji = "🇨🇨", text = "Cocos Islands flag" },
	{ emoji = "🇨🇩", text = "Congo DR flag" },
	{ emoji = "🇨🇫", text = "CAR (Central African Republic) flag" },
	{ emoji = "🇨🇬", text = "Congo Brazzaville flag" },
	{ emoji = "🇨🇭", text = "Switzerland flag" },
	{ emoji = "🇨🇮", text = "Côte d’Ivoire flag" },
	{ emoji = "🇨🇰", text = "Cook Islands flag" },
	{ emoji = "🇨🇱", text = "Chile flag" },
	{ emoji = "🇨🇲", text = "Cameroun flag" },
	{ emoji = "🇨🇳", text = "China flag" },
	{ emoji = "🇨🇴", text = "Columbia flag" },
	{ emoji = "🇨🇵", text = "Clipperton Island flag" },
	{ emoji = "🇨🇷", text = "Costa Rica flag" },
	{ emoji = "🇨🇺", text = "Cuba flag" },
	{ emoji = "🇨🇻", text = "Cape Verde Island flag" },
	{ emoji = "🇨🇼", text = "Curaçao flag" },
	{ emoji = "🇨🇽", text = "Christmas Island flag" },
	{ emoji = "🇨🇾", text = "Cyprus flag" },
	{ emoji = "🇩🇪", text = "Germany flag" },
	{ emoji = "🇩🇬", text = "Diego Garcia flag" },
	{ emoji = "🇩🇯", text = "Djibouti flag" },
	{ emoji = "🇩🇰", text = "Denmark flag" },
	{ emoji = "🇩🇲", text = "Dominica flag" },
	{ emoji = "🇩🇴", text = "Dominican Republic flag" },
	{ emoji = "🇩🇿", text = "Algeria flag" },
	{ emoji = "🇪🇦", text = "Ceuta & Melilla flag" },
	{ emoji = "🇪🇨", text = "Ecuador flag" },
	{ emoji = "🇪🇪", text = "Estonia" },
	{ emoji = "🇪🇬", text = "Egypt flag" },
	{ emoji = "🇪🇭", text = "Western Sahara flag" },
	{ emoji = "🇪🇷", text = "Eritrea flag" },
	{ emoji = "🇪🇸", text = "Spain flag" },
	{ emoji = "🇪🇹", text = "Ethiopia flag" },
	{ emoji = "🇪🇺", text = "EU flag" },
	{ emoji = "🇫🇮", text = "Finland flag" },
	{ emoji = "🇫🇯", text = "Fiji flag" },
	{ emoji = "🇫🇰", text = "Falkland Island flag" },
	{ emoji = "🇫🇲", text = "Micronesia flag" },
	{ emoji = "🇫🇴", text = "Faroe Island flag" },
	{ emoji = "🇫🇷", text = "France flag" },
	{ emoji = "🇬🇦", text = "Gabon flag" },
	{ emoji = "🇬🇧", text = "United Kingdom flag" },
	{ emoji = "🇬🇩", text = "Grenada flag" },
	{ emoji = "🇬🇪", text = "Georgia flag" },
	{ emoji = "🇬🇫", text = "French Guiana flag" },
	{ emoji = "🇬🇬", text = "Guernsey flag" },
	{ emoji = "🇬🇭", text = "Ghana flag" },
	{ emoji = "🇬🇮", text = "Gibraltar flag" },
	{ emoji = "🇬🇱", text = "Greenland flag" },
	{ emoji = "🇬🇲", text = "Gambia flag" },
	{ emoji = "🇬🇳", text = "Guinea flag" },
	{ emoji = "🇬🇵", text = "Guadeloupe flag" },
	{ emoji = "🇬🇶", text = "Equitorial Guinea flag" },
	{ emoji = "🇬🇷", text = "Greece flag" },
	{ emoji = "🇬🇸", text = "South Georgia & South Sandwich Islands flag" },
	{ emoji = "🇬🇹", text = "Guatemala flag" },
	{ emoji = "🇬🇺", text = "Guam flag" },
	{ emoji = "🇬🇼", text = "Guinea Bissau flag" },
	{ emoji = "🇬🇾", text = "Guyana flag" },
	{ emoji = "🇭🇰", text = "Hong Kong flag" },
	{ emoji = "🇭🇲", text = "Heard & McDonald Islands flag" },
	{ emoji = "🇭🇳", text = "Honduras flag" },
	{ emoji = "🇭🇷", text = "Croatia flag" },
	{ emoji = "🇭🇹", text = "Haiti flag" },
	{ emoji = "🇭🇺", text = "Hungary flag" },
	{ emoji = "🇮🇨", text = "Canary Islands flag" },
	{ emoji = "🇮🇩", text = "Indonesia flag" },
	{ emoji = "🇮🇪", text = "Island flag" },
	{ emoji = "🇮🇱", text = "Israel flag" },
	{ emoji = "🇮🇲", text = "Isle of Man flag" },
	{ emoji = "🇮🇳", text = "India flag" },
	{ emoji = "🇮🇴", text = "British Indian Ocean Territory flag" },
	{ emoji = "🇮🇶", text = "Iraq flag" },
	{ emoji = "🇮🇷", text = "Iran flag" },
	{ emoji = "🇮🇸", text = "Iceland flag" },
	{ emoji = "🇮🇹", text = "Italy flag" },
	{ emoji = "🇯🇪", text = "Jersey flag" },
	{ emoji = "🇯🇲", text = "Jamaica flag" },
	{ emoji = "🇯🇴", text = "Jordan flag" },
	{ emoji = "🇯🇵", text = "Japan flag" },
	{ emoji = "🇰🇪", text = "Kenya flag" },
	{ emoji = "🇰🇬", text = "Kyrgyzstan flag" },
	{ emoji = "🇰🇭", text = "Cambodia flag" },
	{ emoji = "🇰🇮", text = "Kiribati flag" },
	{ emoji = "🇰🇲", text = "Comoros Island flag" },
	{ emoji = "🇰🇳", text = "St. Kitts & Nevis Flag" },
	{ emoji = "🇰🇵", text = "North Korea flag" },
	{ emoji = "🇰🇷", text = "South Korea flag" },
	{ emoji = "🇰🇼", text = "Kuwait flag" },
	{ emoji = "🇰🇾", text = "Cayman Island flag" },
	{ emoji = "🇰🇿", text = "Kazakhstan flag" },
	{ emoji = "🇱🇦", text = "Laos flag" },
	{ emoji = "🇱🇧", text = "Lebanon flag" },
	{ emoji = "🇱🇨", text = "St. Lucia flag" },
	{ emoji = "🇱🇮", text = "Liechtenstein flag" },
	{ emoji = "🇱🇰", text = "Sri Lanka flag" },
	{ emoji = "🇱🇷", text = "Liberia flag" },
	{ emoji = "🇱🇸", text = "Lesotho flag" },
	{ emoji = "🇱🇹", text = "LIthuania flag" },
	{ emoji = "🇱🇻", text = "Latvia flag" },
	{ emoji = "🇱🇾", text = "Libya flag" },
	{ emoji = "🇲🇦", text = "Morocco flag" },
	{ emoji = "🇲🇨", text = "Monaco flag" },
	{ emoji = "🇲🇩", text = "Moldova flag" },
	{ emoji = "🇲🇪", text = "Montenegro flag" },
	{ emoji = "🇲🇬", text = "Montenegro flag" },
	{ emoji = "🇲🇭", text = "Marshall Islands flag" },
	{ emoji = "🇲🇰", text = "North Macedonia flag" },
	{ emoji = "🇲🇱", text = "Mali flag" },
	{ emoji = "🇲🇲", text = "Myanmar flag" },
	{ emoji = "🇲🇳", text = "Mongolia flag" },
	{ emoji = "🇲🇴", text = "Macao flag" },
	{ emoji = "🇲🇵", text = "Northern Mariana Islands flag" },
	{ emoji = "🇲🇶", text = "Marthinique flag" },
	{ emoji = "🇲🇷", text = "Mauritania flag" },
	{ emoji = "🇲🇸", text = "Montserrat flag" },
	{ emoji = "🇲🇹", text = "Malta flag" },
	{ emoji = "🇲🇺", text = "Mauritius flag" },
	{ emoji = "🇲🇻", text = "Maldives flag" },
	{ emoji = "🇲🇼", text = "Malawi flag" },
	{ emoji = "🇲🇽", text = "Mexico flag" },
	{ emoji = "🇲🇾", text = "Malaysia flag" },
	{ emoji = "🇲🇿", text = "Mozambique flag" },
	{ emoji = "🇳🇦", text = "Namibia flag" },
	{ emoji = "🇳🇨", text = "New Caledonia flag" },
	{ emoji = "🇳🇪", text = "Niger flag" },
	{ emoji = "🇳🇫", text = "Norfolk Island flag" },
	{ emoji = "🇳🇬", text = "Nigeria flag" },
	{ emoji = "🇳🇮", text = "Nicaragua flag" },
	{ emoji = "🇳🇱", text = "Netherlands flag" },
	{ emoji = "🇳🇴", text = "Norway flag" },
	{ emoji = "🇳🇵", text = "Nepal flag" },
	{ emoji = "🇳🇷", text = "Nauru flag" },
	{ emoji = "🇳🇺", text = "Niue flag" },
	{ emoji = "🇳🇿", text = "New Zealand flag" },
	{ emoji = "🇴🇲", text = "Oman flag" },
	{ emoji = "🇵🇦", text = "Panama flag" },
	{ emoji = "🇵🇪", text = "Peru flag" },
	{ emoji = "🇵🇫", text = "French Polynesia flag" },
	{ emoji = "🇵🇬", text = "Papua New Guinea flag" },
	{ emoji = "🇵🇭", text = "Philipines flag" },
	{ emoji = "🇵🇰", text = "Pakistan flag" },
	{ emoji = "🇵🇱", text = "Poland flag" },
	{ emoji = "🇵🇲", text = "St. Pierre & Miquelon" },
	{ emoji = "🇵🇳", text = "Pitcairn Islands flag" },
	{ emoji = "🇵🇷", text = "Puerto Rico flag" },
	{ emoji = "🇵🇸", text = "Palestinian Territories flag" },
	{ emoji = "🇵🇹", text = "Portugal flag" },
	{ emoji = "🇵🇼", text = "Palau flag" },
	{ emoji = "🇵🇾", text = "Paraguay flag" },
	{ emoji = "🇶🇦", text = "Qatar flag" },
	{ emoji = "🇷🇪", text = "Réunion flag" },
	{ emoji = "🇷🇸", text = "Serbia flag" },
	{ emoji = "🇷🇺", text = "Russia flag" },
	{ emoji = "🇷🇼", text = "Rwanda flag" },
	{ emoji = "🇸🇦", text = "Saudi Arabia flag" },
	{ emoji = "🇸🇧", text = "Solomon Islands" },
	{ emoji = "🇸🇨", text = "Seychelles flag" },
	{ emoji = "🇸🇩", text = "Sudan flag" },
	{ emoji = "🇸🇪", text = "Sweeden flag" },
	{ emoji = "🇸🇬", text = "Singapore flag" },
	{ emoji = "🇸🇭", text = "St. Helena flag" },
	{ emoji = "🇸🇮", text = "Slovenia flag" },
	{ emoji = "🇸🇯", text = "Svalbard & Jan Mayen" },
	{ emoji = "🇸🇰", text = "Slovakia flag" },
	{ emoji = "🇸🇱", text = "Sierra Leone flag" },
	{ emoji = "🇸🇲", text = "San Marino flag" },
	{ emoji = "🇸🇳", text = "Senegal flag" },
	{ emoji = "🇸🇴", text = "Somalia flag" },
	{ emoji = "🇸🇷", text = "Suriname flag" },
	{ emoji = "🇸🇸", text = "South Sudan flag" },
	{ emoji = "🇸🇹", text = "São Tomé & Príncipe flag" },
	{ emoji = "🇸🇻", text = "El Salvador flag" },
	{ emoji = "🇸🇽", text = "Saint Maarten flag" },
	{ emoji = "🇸🇾", text = "Syria flag" },
	{ emoji = "🇸🇿", text = "Eswatini (Swaziland) flag" },
	{ emoji = "🇹🇦", text = "Tristan da Cunha flag" },
	{ emoji = "🇹🇨", text = "Turks & Caicos Islands flag" },
	{ emoji = "🇹🇩", text = "Chad flag" },
	{ emoji = "🇹🇫", text = "French Southern Territories flag" },
	{ emoji = "🇹🇬", text = "Togo flag" },
	{ emoji = "🇹🇭", text = "Thailand flag" },
	{ emoji = "🇹🇯", text = "Tajikistan flag" },
	{ emoji = "🇹🇰", text = "Tokelau flag" },
	{ emoji = "🇹🇱", text = "Timor-Leste flag" },
	{ emoji = "🇹🇲", text = "Turkmenistan flag" },
	{ emoji = "🇹🇳", text = "Tunisia flag" },
	{ emoji = "🇹🇴", text = "Tonga flag" },
	{ emoji = "🇹🇷", text = "Turkey flag" },
	{ emoji = "🇹🇹", text = "Trinidad and Tobago flag" },
	{ emoji = "🇹🇻", text = "Tuvalu flag" },
	{ emoji = "🇹🇼", text = "Taiwan flag" },
	{ emoji = "🇹🇿", text = "Tanzania flag" },
	{ emoji = "🇺🇦", text = "Ukraine flag" },
	{ emoji = "🇺🇬", text = "Uganda flag" },
	{ emoji = "🇺🇲", text = "US Outlying Islands flag" },
	{ emoji = "🇺🇳", text = "United Nations (UN) flag" },
	{ emoji = "🇺🇸", text = "United State flag" },
	{ emoji = "🇺🇾", text = "Uruguay flag" },
	{ emoji = "🇺🇿", text = "Uzbekistan flag" },
	{ emoji = "🇻🇦", text = "Vatical City flag" },
	{ emoji = "🇻🇨", text = "St. Vincent & Grenadines flag" },
	{ emoji = "🇻🇪", text = "Venezuela flag" },
	{ emoji = "🇻🇬", text = "British Virgin Islands flag" },
	{ emoji = "🇻🇮", text = "U.S. Virgin Islands" },
	{ emoji = "🇻🇮", text = "Vietnam flag" },
	{ emoji = "🇻🇺", text = "Vanuatu flag" },
	{ emoji = "🇼🇫", text = "Wallis & Futuna flag" },
	{ emoji = "🇼🇸", text = "Samoa flag" },
	{ emoji = "🇽🇰", text = "Kosovo flag" },
	{ emoji = "🇾🇪", text = "Yemen flag" },
	{ emoji = "🇾🇹", text = "Mayotte flag" },
	{ emoji = "🇿🇦", text = "South Africa flag" },
	{ emoji = "🇿🇲", text = "Zambia flag" },
	{ emoji = "🇿🇼", text = "Zimbabwe flag" },
}

source.complete = function(self, request, callback)
	local input = string.sub(request.context.cursor_before_line, request.offset - 1)

	local items = {}
	for key, value in pairs(emojis) do
		table.insert(items, {
			filterText = value.text,
			label = value.text .. " - " .. value.emoji,
			textEdit = {
				newText = value.emoji,
				range = {
					start = {
						line = request.context.cursor.row - 1,
						character = request.context.cursor.col - 1 - #input,
					},
					["end"] = {
						line = request.context.cursor.row - 1,
						character = request.context.cursor.col - 1,
					},
				},
			},
		})
	end
	callback({
		items = items,
		isIncomplete = true,
	})
end

-- import nvim-cmp plugin safely
local cmp_status, cmp = pcall(require, "cmp")
if not cmp_status then
	return
end

-- register emojis source
cmp.register_source("emojis", source.new())
