local source = {}

source.new = function()
	return setmetatable({}, { __index = source })
end

local emojis = {
	{ emoji = "😀", text = "Grinning Face" },
	{ emoji = "😃", text = "Grinning Face with Big Eyes" },
	{ emoji = "😄", text = "Grinning Face with Smiling Eyes" },
	{ emoji = "😁", text = "Beaming Face with Smiling Eyes" },
	{ emoji = "😆", text = "Grinning Squinting Face" },
	{ emoji = "😅", text = "Grinning Face with Sweat" },
	{ emoji = "🤣", text = "Rolling on the Floor Laughing" },
	{ emoji = "😂", text = "Face with Tears of Joy" },
	{ emoji = "🙂", text = "Slightly Smiling Face" },
	{ emoji = "🙃", text = "Upside-Down Face" },
	{ emoji = "🫠", text = "Melting Face" },
	{ emoji = "😉", text = "Winking Face" },
	{ emoji = "😊", text = "Smiling Face with Smiling Eyes" },
	{ emoji = "😇", text = "Smiling Face with Halo" },
	{ emoji = "🥰", text = "Smiling Face with Hearts" },
	{ emoji = "😍", text = "Smiling Face with Heart-Eyes" },
	{ emoji = "🤩", text = "Star-Struck" },
	{ emoji = "😘", text = "Face Blowing a Kiss" },
	{ emoji = "😗", text = "Kissing Face" },
	{ emoji = "☺️ ", text = "Smiling Face" },
	{ emoji = "😚", text = "Kissing Face with Closed Eyes" },
	{ emoji = "😙", text = "Kissing Face with Smiling Eyes" },
	{ emoji = "🥲", text = "Smiling Face with Tear" },
	{ emoji = "😋", text = "Face Savoring Food" },
	{ emoji = "😛", text = "Face with Tongue" },
	{ emoji = "😜", text = "Winking Face with Tongue" },
	{ emoji = "🤪", text = "Zany Face" },
	{ emoji = "😝", text = "Squinting Face with Tongue" },
	{ emoji = "🤑", text = "Money-Mouth Face" },
	{ emoji = "🤗", text = "Smiling Face with Open Hands" },
	{ emoji = "🤭", text = "Face with Hand Over Mouth" },
	{ emoji = "🫢", text = "Face with Open Eyes and Hand Over Mouth" },
	{ emoji = "🫣", text = "Face with Peeking Eye" },
	{ emoji = "🤫", text = "Shushing Face" },
	{ emoji = "🤔", text = "Thinking Face" },
	{ emoji = "🫡", text = "Saluting Face" },
	{ emoji = "🤐", text = "Zipper-Mouth Face" },
	{ emoji = "🤨", text = "Face with Raised Eyebrow" },
	{ emoji = "😐", text = "Neutral Face" },
	{ emoji = "😑", text = "Expressionless Face" },
	{ emoji = "😶", text = "Face Without Mouth" },
	{ emoji = "🫥", text = "Dotted Line Face" },
	{ emoji = "😶", text = "Face in Clouds" },
	{ emoji = "😏", text = "Smirking Face" },
	{ emoji = "😒", text = "Unamused Face" },
	{ emoji = "🙄", text = "Face with Rolling Eyes" },
	{ emoji = "😬", text = "Grimacing Face" },
	{ emoji = "😮", text = "Face Exhaling" },
	{ emoji = "🤥", text = "Lying Face" },
	{ emoji = "😌", text = "Relieved Face" },
	{ emoji = "😔", text = "Pensive Face" },
	{ emoji = "😪", text = "Sleepy Face" },
	{ emoji = "🤤", text = "Drooling Face" },
	{ emoji = "😴", text = "Sleeping Face" },
	{ emoji = "😷", text = "Face with Medical Mask" },
	{ emoji = "🤒", text = "Face with Thermometer" },
	{ emoji = "🤕", text = "Face with Head-Bandage" },
	{ emoji = "🤢", text = "Nauseated Face" },
	{ emoji = "🤮", text = "Face Vomiting" },
	{ emoji = "🤧", text = "Sneezing Face" },
	{ emoji = "🥵", text = "Hot Face" },
	{ emoji = "🥶", text = "Cold Face" },
	{ emoji = "🥴", text = "Woozy Face" },
	{ emoji = "😵", text = "Face with Crossed-Out Eyes" },
	{ emoji = "😵", text = "💫 Face with Spiral Eyes" },
	{ emoji = "🤯", text = "Exploding Head" },
	{ emoji = "🤠", text = "Cowboy Hat Face" },
	{ emoji = "🥳", text = "Partying Face" },
	{ emoji = "🥸", text = "Disguised Face" },
	{ emoji = "😎", text = "Smiling Face with Sunglasses" },
	{ emoji = "🤓", text = "Nerd Face" },
	{ emoji = "🧐", text = "Face with Monocle" },
	{ emoji = "😕", text = "Confused Face" },
	{ emoji = "🫤", text = "Face with Diagonal Mouth" },
	{ emoji = "😟", text = "Worried Face" },
	{ emoji = "🙁", text = "Slightly Frowning Face" },
	{ emoji = "☹️", text = "Frowning Face" },
	{ emoji = "😮", text = "Face with Open Mouth" },
	{ emoji = "😯", text = "Hushed Face" },
	{ emoji = "😲", text = "Astonished Face" },
	{ emoji = "😳", text = "Flushed Face" },
	{ emoji = "🥺", text = "Pleading Face" },
	{ emoji = "🥹", text = "Face Holding Back Tears" },
	{ emoji = "😦", text = "Frowning Face with Open Mouth" },
	{ emoji = "😧", text = "Anguished Face" },
	{ emoji = "😨", text = "Fearful Face" },
	{ emoji = "😰", text = "Anxious Face with Sweat" },
	{ emoji = "😥", text = "Sad but Relieved Face" },
	{ emoji = "😢", text = "Crying Face" },
	{ emoji = "😭", text = "Loudly Crying Face" },
	{ emoji = "😱", text = "Face Screaming in Fear" },
	{ emoji = "😖", text = "Confounded Face" },
	{ emoji = "😣", text = "Persevering Face" },
	{ emoji = "😞", text = "Disappointed Face" },
	{ emoji = "😓", text = "Downcast Face with Sweat" },
	{ emoji = "😩", text = "Weary Face" },
	{ emoji = "😫", text = "Tired Face" },
	{ emoji = "🥱", text = "Yawning Face" },
	{ emoji = "😤", text = "Face with Steam From Nose" },
	{ emoji = "😡", text = "Enraged Face" },
	{ emoji = "😠", text = "Angry Face" },
	{ emoji = "🤬", text = "Face with Symbols on Mouth" },
	{ emoji = "😈", text = "Smiling Face with Horns" },
	{ emoji = "👿", text = "Angry Face with Horns" },
	{ emoji = "💀", text = "Skull" },
	{ emoji = "☠️", text = "Skull and Crossbones" },
	{ emoji = "💩", text = "Pile of Poo" },
	{ emoji = "🤡", text = "Clown Face" },
	{ emoji = "👹", text = "Ogre" },
	{ emoji = "👺", text = "Goblin" },
	{ emoji = "👻", text = "Ghost" },
	{ emoji = "👽", text = "Alien" },
	{ emoji = "👾", text = "Alien Monster" },
	{ emoji = "🤖", text = "Robot" },
	{ emoji = "😺", text = "Grinning Cat" },
	{ emoji = "😸", text = "Grinning Cat with Smiling Eyes" },
	{ emoji = "😹", text = "Cat with Tears of Joy" },
	{ emoji = "😻", text = "Smiling Cat with Heart-Eyes" },
	{ emoji = "😼", text = "Cat with Wry Smile" },
	{ emoji = "😽", text = "Kissing Cat" },
	{ emoji = "🙀", text = "Weary Cat" },
	{ emoji = "😿", text = "Crying Cat" },
	{ emoji = "😾", text = "Pouting Cat" },
	{ emoji = "💋", text = "Kiss Mark" },
	{ emoji = "👋", text = "Waving Hand" },
	{ emoji = "🤚", text = "Raised Back of Hand" },
	{ emoji = "🖐️", text = "Hand with Fingers Splayed" },
	{ emoji = "✋", text = "Raised Hand" },
	{ emoji = "🫶", text = "Heart Hands" },
	{ emoji = "👐", text = "Open Hands" },
	{ emoji = "🤲", text = "Palms Up Together" },
	{ emoji = "🤝", text = "Handshake" },
	{ emoji = "🙏", text = "Folded Hands" },
	{ emoji = "✍️", text = "Writing Hand" },
	{ emoji = "💅", text = "Nail Polish" },
	{ emoji = "🤳", text = "Selfie" },
	{ emoji = "💪", text = "Flexed Biceps" },
	{ emoji = "🦾", text = "Mechanical Arm" },
	{ emoji = "🦿", text = "Mechanical Leg" },
	{ emoji = "🦵", text = "Leg" },
	{ emoji = "🧠", text = "Brain" },
	{ emoji = "🫀", text = "Anatomical Heart" },
	{ emoji = "🫁", text = "Lungs" },
	{ emoji = "🦷", text = "Tooth" },
	{ emoji = "🦴", text = "Bone" },
	{ emoji = "👀", text = "Eyes" },
	{ emoji = "🤷", text = "Person Shrugging" },
	{ emoji = "👮", text = "Police Officer" },
	{ emoji = "🕵️", text = "Detective" },
	{ emoji = "💂", text = "Guard" },
	{ emoji = "🥷", text = "Ninja" },
	{ emoji = "👷", text = "Construction Worker" },
	{ emoji = "👼", text = "Baby Angel" },
	{ emoji = "🎅", text = "Santa Claus" },
	{ emoji = "🤶", text = "Mrs. Claus" },
	{ emoji = "🦸", text = "Superhero" },
	{ emoji = "🦹", text = "Supervillain" },
	{ emoji = "🧙", text = "Mage" },
	{ emoji = "🧚", text = "Fairy" },
	{ emoji = "🧛", text = "Vampire" },
	{ emoji = "🧜", text = "Merperson" },
	{ emoji = "🧝", text = "Elf" },
	{ emoji = "🧞", text = "Genie" },
	{ emoji = "🧟", text = "Zombie" },
	{ emoji = "🧌", text = "Troll" },
	{ emoji = "💆", text = "Person Getting Massage" },
	{ emoji = "💇", text = "Person Getting Haircut" },
	{ emoji = "🚶", text = "Person Walking" },
	{ emoji = "🧍", text = "Person Standing" },
	{ emoji = "🧎", text = "Person Kneeling" },
	{ emoji = "🏃", text = "Person Running" },
	{ emoji = "💃", text = "Woman Dancing" },
	{ emoji = "🕺", text = "Man Dancing" },
	{ emoji = "🕴️", text = "Person in Suit Levitating" },
	{ emoji = "👯", text = "People with Bunny Ears" },
	{ emoji = "🧖", text = "Person in Steamy Room" },
	{ emoji = "🧘", text = "Person in Lotus Position" },
	{ emoji = "👭", text = "Women Holding Hands" },
	{ emoji = "👫", text = "Woman and Man Holding Hands" },
	{ emoji = "👬", text = "Men Holding Hands" },
	{ emoji = "💏", text = "Kiss" },
	{ emoji = "💑", text = "Couple with Heart" },
	{ emoji = "👪", text = "Family" },
	{ emoji = "🗣️", text = "Speaking Head" },
	{ emoji = "👤", text = "Bust in Silhouette" },
	{ emoji = "👥", text = "Busts in Silhouette" },
	{ emoji = "🫂", text = "People Hugging" },
	{ emoji = "👣", text = "Footprints" },
	{ emoji = "🧳", text = "Luggage" },
	{ emoji = "🌂", text = "Closed Umbrella" },
	{ emoji = "☂️", text = "Umbrella" },
	{ emoji = "🎃", text = "Jack-O-Lantern" },
	{ emoji = "🧵", text = "Thread" },
	{ emoji = "🧶", text = "Yarn" },
	{ emoji = "👓", text = "Glasses" },
	{ emoji = "🕶️", text = "Sunglasses" },
	{ emoji = "🥽", text = "Goggles" },
	{ emoji = "🥼", text = "Lab Coat" },
	{ emoji = "🦺", text = "Safety Vest" },
	{ emoji = "👔", text = "Necktie" },
	{ emoji = "👕", text = "T-Shirt" },
	{ emoji = "👖", text = "Jeans" },
	{ emoji = "🧣", text = "Scarf" },
	{ emoji = "🧤", text = "Gloves" },
	{ emoji = "🧥", text = "Coat" },
	{ emoji = "🧦", text = "Socks" },
	{ emoji = "👗", text = "Dress" },
	{ emoji = "👘", text = "Kimono" },
	{ emoji = "🥻", text = "Sari" },
	{ emoji = "🩱", text = "One-Piece Swimsuit" },
	{ emoji = "🩲", text = "Briefs" },
	{ emoji = "🩳", text = "Shorts" },
	{ emoji = "👙", text = "Bikini" },
	{ emoji = "👚", text = "Woman’s Clothes" },
	{ emoji = "👛", text = "Purse" },
	{ emoji = "👜", text = "Handbag" },
	{ emoji = "👝", text = "Clutch Bag" },
	{ emoji = "🎒", text = "Backpack" },
	{ emoji = "🩴", text = "Thong Sandal" },
	{ emoji = "👞", text = "Man’s Shoe" },
	{ emoji = "👟", text = "Running Shoe" },
	{ emoji = "🥾", text = "Hiking Boot" },
	{ emoji = "🥿", text = "Flat Shoe" },
	{ emoji = "👠", text = "High-Heeled Shoe" },
	{ emoji = "👡", text = "Woman’s Sandal" },
	{ emoji = "🩰", text = "Ballet Shoes" },
	{ emoji = "👢", text = "Woman’s Boot" },
	{ emoji = "👑", text = "Crown" },
	{ emoji = "👒", text = "Woman’s Hat" },
	{ emoji = "🎩", text = "Top Hat" },
	{ emoji = "🎓", text = "Graduation Cap" },
	{ emoji = "🧢", text = "Billed Cap" },
	{ emoji = "🪖", text = "Military Helmet" },
	{ emoji = "⛑️", text = "Rescue Worker’s Helmet" },
	{ emoji = "💄", text = "Lipstick" },
	{ emoji = "💍", text = "Ring" },
	{ emoji = "💼", text = "Briefcase" },
	{ emoji = "🩸", text = "Drop of Blood" },
}

source.complete = function(self, request, callback)
	local input = string.sub(request.context.cursor_before_line, request.offset - 1)

	local items = {}
	for key, value in pairs(emojis) do
		table.insert(items, {
			filterText = value.text,
			label = value.text .. " - " .. value.emoji,
			textEdit = {
				newText = value.emoji,
				range = {
					start = {
						line = request.context.cursor.row - 1,
						character = request.context.cursor.col - 1 - #input,
					},
					["end"] = {
						line = request.context.cursor.row - 1,
						character = request.context.cursor.col - 1,
					},
				},
			},
		})
	end
	callback({
		items = items,
		isIncomplete = true,
	})
end

-- import nvim-cmp plugin safely
local cmp_status, cmp = pcall(require, "cmp")
if not cmp_status then
	return
end

-- register emojis source
cmp.register_source("emojis", source.new())
